- src/main/java/io/javalin/Response.java
- src/main/java/io/javalin/core/JavalinServlet.java
- src/main/java/io/javalin/core/util/Util.java
- src/test/java/io/javalin/TestResponse.java
This adds Response.body(InputStream).  There can be only one body, so calling body(String) clears any previously set InputStream, and vice-versa.  Added a unit test as well.
> re #4: implement Response.body(InputStream)

- src/main/java/io/javalin/Context.kt
In the Java's _"Programming into the Future"_ world, the `CompletionStage` is the global interface to use as return type (would be `Future` in _Scala_). The `CompletableFuture` is the concrete object to use to create __and control__ the `CompletionStage` (would be `Promise` in _Scala_). A method providing "a value in the future" has no reason to return a `CompletableFuture`, since the caller of that method could decide to completable that Future himself.
In the context of the Javalin's `Context`, the `async` method expects the user of the library to provide "something in the future" and is only interested in when it finishes. In this context, a `CompletionStage<Void>` (could be `<Unit>` to be more Kotlin-ish) is enough.
I propose this modification on a use-case basis. When using _Javalin_ …
> `async` expects a `CompletionStage` instead of a `CompletableFuture`

- src/main/java/io/javalin/Javalin.java
- src/main/java/io/javalin/core/JavalinServlet.kt
- src/main/java/io/javalin/embeddedserver/CachedRequestWrapper.kt
- src/test/java/io/javalin/TestRequestCache.java
Initialize cache in request lazily, so the original stream will not be drained.
#131 and #116
> Allow configuration of request body cache

- pom.xml
jre8 package is deprecated in favor of jdk8 now.
> Update kotlin-stdlib-jre8 to kotlin-stdlib-jdk8.

- src/main/java/io/javalin/embeddedserver/jetty/EmbeddedJettyServer.kt
- src/main/java/io/javalin/embeddedserver/jetty/websocket/RootWebSocketCreator.kt
See #174 
Now javalin sends a 404 to all upgrade-requests that can't be mapped.
```
curl --include \
--no-buffer \
--header "Connection: Upgrade" \
--header "Upgrade: websocket" \
--header "Host: localhost:7000" \
--header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
--header "Sec-WebSocket-Version: 13" \
http://localhost:7000/context-path/not/a/valid/path
```
```
HTTP/1.1 404 Not found
Date: Mon, 19 Mar 2018 15:34:03 GMT
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1
Content-Length: 345
Server: Jetty(9.4.8.v20171121)
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /context-path/not/a/valid/path. Reason:
<pre>    Not …
```
> Return 404 if the websocket request cannot be mapped.

- src/main/java/io/javalin/embeddedserver/jetty/websocket/WebSocketCreators.kt
- src/main/java/io/javalin/embeddedserver/jetty/websocket/WebSocketHandler.java
Instead of querying the path-parameters every time a `WsSession` is created, it's more performant to query the parameter only during the handshake.
> Small performance improvements for WebSockets.

- src/main/java/io/javalin/core/util/LogUtil.kt
Not having this inside the `when` gives a warning, and I like covering all cases.
> Add default branch for LogLevel.OFF

- src/main/java/io/javalin/Javalin.java
- src/main/java/io/javalin/core/PathMatcher.kt
- win in performance in usual path matching (less paths to check)
- lose in performance in reverse routing (need to transform routes from map)
> Use EnumMap in handler matcher

- src/main/java/io/javalin/Extension.java
- src/main/java/io/javalin/Javalin.java
- src/test/java/io/javalin/TestExtension.java
Hi,
this change adds a `register()` method similar to [sinatras register DSL](http://sinatrarb.com/extensions.html#extending-the-dsl-class-context-with-sinatraregister).
The motivation is to write a feature module and reflect the cohesiveness of the feature in the cohesiveness of the source code. Code that belongs to the same feature should be grouped closely together and written in source files next to each other.
Something similar is already possible with the endpoint groups (handler groups) but extensions give access to the `Javalin` app instance. Extensions should be especially helpful for cross-cutting concerns, e.g. adding a persistence data layer to an application, or adding a complex authentication feature (one that adds an access manager and a login/logout route and possibly adds …
> [extension] add Extension API

- src/main/java/io/javalin/Javalin.java
- src/main/java/io/javalin/core/HandlerType.kt
- src/main/java/io/javalin/core/JavalinServlet.kt
- src/main/java/io/javalin/core/util/MethodNotAllowedUtil.kt
- src/test/java/io/javalin/TestMethodNotAllowed.java
This pull request implements the feature requested in the issue #228 and adds a new test case. I've made the feature toggable and disabled by default to preserve backwards compatibility. I'm open to any suggestions on how this can be improved.
> [core] Return 405 instead of 404 when applicable

- src/main/java/io/javalin/Context.kt
ctx.uri() duplicates method ctx.path() #239
> Removing duplicate method ctx.uri()

- src/main/java/io/javalin/rendering/JavalinRenderer.kt
Adds the `.twig` extension as a default
> [core] Add the '.twig' extension as a default recognized jTwig template

- src/main/java/io/javalin/HaltException.kt
The purpose of this PR is to remove the default body message (`Execution halted`) from the `HaltException`.
The message itself doesn't relay any sort of useful information outside of a debug environment. When short-circuiting logic i was often finding myself writing code to remove the default message, for example:
```java
if (message == null) {
throw new HaltException(HttpServletResponse.SC_NOT_FOUND, "");
}
```
If anyone has any objections, please post it.
> [core] Remove default body from HaltException

- src/main/java/io/javalin/core/util/JettyServerUtil.kt
Previously log always said Jetty was listening on localhost.
> [core] Log correct host/IP that Jetty is listening on. (#289)

- src/main/java/io/javalin/core/util/JettyServerUtil.kt
I forgot to test bd13123388ab0f5c9ec3f9f8d09f64d636d3cb5b with the default (no host) config. Fixed.
> [core] log "localhost" instead of null when host not set (#289)

- src/main/java/io/javalin/core/util/JettyServerUtil.kt
- src/test/java/io/javalin/TestGracefulShutdown.java
This pull request is concerned with adding support for configuring Jetty with a graceful shutdown handler by default as identified in issue #286. This PR will include a functional test to validate whether the functionality has been added, and will also include an implementation of the configuration changes required.
> Add Graceful Jetty Shutdown Feature (RE: #286)

- src/main/java/io/javalin/Javalin.java
- src/main/java/io/javalin/core/JavalinServlet.kt
- src/main/java/io/javalin/core/util/ContextUtil.kt
- src/main/java/io/javalin/core/util/MethodNotAllowedUtil.kt
- src/main/java/io/javalin/core/util/SinglePageHandler.kt
- src/main/java/io/javalin/core/util/SwaggerRenderer.kt
- src/main/java/io/javalin/core/util/Util.kt
- src/test/java/io/javalin/TestMethodNotAllowed.kt
- src/test/java/io/javalin/TestSinglePageMode.kt
- src/test/java/io/javalin/TestStaticFiles.kt
- src/test/java/io/javalin/util/HttpUtil.kt
There are two main ways of doing routing for a SPA, hash/fragment (`#`) and push-state. When the user navigates the SPA you'll end up with one of two URL patterns: 
```
myapp.com/#/users/tipsy // hash
myapp.com/users/tipsy // pushstate
```
Currently there isn't any elegant way of handling these client side routes in Javalin. A common pattern is to redirect 404's to the apps entry-point (`index.html`). Another pattern is to route all requests without extensions to the entry point (won't work if you're hosting your API on the same service.
This PR adds a `enableSinglePageMode(path, filePath)`. This would return the content of `filePath` for all calls that would normally result in a 404 on the `path` (given that the client making the call accepts HTML). It would not involve a redirect.
HTML …
> [core] Add single page mode

- src/main/java/io/javalin/apibuilder/ApiBuilder.java
- src/test/java/io/javalin/TestApiBuilder.kt
Fixes #337
This allows using wildcards in `ApiBuilder::crud` paths without
`CrudHandler::getAll` being called for singular `get` calls.
> Fix wildcards in crud

- src/main/java/io/javalin/Context.kt
- src/main/java/io/javalin/core/util/LogUtil.kt
- src/test/java/io/javalin/TestRequest.kt
Fixes #343
Session and request attributes now expressively return nullable types to
indicate that an attribute might not have been set.
> Context attributes now return nullable types

- src/main/java/io/javalin/Context.kt
- src/test/java/io/javalin/TestFuture.kt
- src/test/kotlin/io/javalin/examples/HelloWorldAsync.kt
The updates include:
- Adding function Context.json(CompletableFuture<*>)
- Updating HelloWorldAsync.kt to have one example using Context.result() and one for Context.json()
- Updating TestFuture.kt to include one case for testing the happy case of Context.json(); failure cases are already covered for Context.result() which is called by Context.json()
> Update to solve issue #352 (Support for passing CompletableFuture to Context.json())

- src/main/java/io/javalin/staticfiles/JettyResourceHandler.kt
Previously Javalin would mark any file with path starting with "/immutable" as immutable; this patch requires files to be in a directory named exactly "immutable" as the docs specify.
Fixes #369.
> Make immutable path matching exact

- pom.xml
- src/main/java/io/javalin/core/util/OptionalDependency.kt
- src/main/java/io/javalin/core/util/Util.kt
- src/main/java/io/javalin/json/JavalinJackson.kt
I took a stab at checking for "kotlin.Metadata" and adding an extra dependency check for `jackson-module-kotlin`.
It seemed to work for this test case. When the `jackson-module-kotlin` dependency is missing an error message is printed to the JVM console (not returned to the client though). When the dependency exists, the application runs correctly.
```kotlin
data class User(val id: Int, val name: String, val sign: String)
fun main(args: Array<String>) {
val data = mutableMapOf(
1 to User(1, "will", "Aries"),
2 to User(2, "corey", "Virgo")
)
// Create a server and start it.
val app = Javalin.create().start(7000)
// Endpoint handlers
app.get("/") { ctx -> ctx.result("Hello World") }
app.get("/user/:id") { ctx ->
val id = ctx.pathParam("id").toInt()
data[id]?.let {
ctx.json(it)
} ?: …
```
> Check for kotlin class when using Jackson

- src/main/java/io/javalin/ErrorHandler.java
- src/main/java/io/javalin/ExceptionHandler.java
- src/main/java/io/javalin/Handler.java
- src/main/java/io/javalin/RequestLogger.java
- src/main/java/io/javalin/rendering/FileRenderer.java
- src/main/java/io/javalin/security/AccessManager.java
- src/main/java/io/javalin/websocket/BinaryMessageHandler.java
- src/main/java/io/javalin/websocket/CloseHandler.java
- src/main/java/io/javalin/websocket/ConnectHandler.java
- src/main/java/io/javalin/websocket/ErrorHandler.java
- src/main/java/io/javalin/websocket/MessageHandler.java
- src/test/java/io/javalin/routeoverview/TestRouteOverview_Kotlin.kt
I annotated everything with `@NotNull` that did not have an annotation yet in the java interfaces.
Two spots actually expect a nullable type for one parameter each. I annotated them with `@Nullable` from the `org.jetbrains.annotations` package.
One "Test" did not compile because he actually expected a nullable context. I changed that single location to expect a non-null context.
> Add missing nullability annotations to the Java interfaces

- src/main/java/io/javalin/Javalin.java
* enableCaseSensitiveUrls did not check the usage although the
documentation indicated otherwise
* Some methods did check the usage but did not indicate it in the
documentation
> Verify usage of some methods to be before starting

- src/main/java/io/javalin/core/util/HttpResponseExceptionMapper.kt
- src/test/java/io/javalin/TestHttpResponseExceptions.kt
I added the suggested solution from #405 with a small test.
> ExceptionMapper is now affected by defaultContentType. Fixes #405

- src/test/java/io/javalin/TestCustomJetty.kt
The existing test leaves a directory in `/tmp` or equivalent.
> [tests] Delete temporary session directory after test run

- src/main/java/io/javalin/Javalin.java
- src/main/java/io/javalin/core/util/Util.kt
Chose `IllegalStateException` as this was also used other places for similar (boot time check) things.
Merely looking up a random UUID should be "non-intrusive" enough so that it's acceptable that the application does this on boot.
> Validate session handler on start (#391)

- src/main/java/io/javalin/core/util/JettyServerUtil.kt
For user klicking in their IDE on the link which is displayed on startup ("Jetty is listening on...") now honors default context path
> Small startup usability improvement

- src/main/java/io/javalin/websocket/WsSession.kt
- src/test/java/io/javalin/TestWebSocket.kt
Nullability is now explicit and queryParam and queryParamMap now don't crash with a NPE.
> WsSession#queryString() improvements (fixes #419)

- src/main/java/io/javalin/core/ExceptionMapper.kt
- src/test/java/io/javalin/TestJson.kt
Test also fixed. Now handling an uncaught exception with the HttpResponseExceptionMapper (InternalServerErrorResponse). Correctly handling defaultContentType.
> Fixed small bug with uncaught exception and default content type

- src/main/java/io/javalin/Context.kt
- src/main/java/io/javalin/core/util/ContextUtil.kt
- src/test/java/io/javalin/TestRequest.kt
I'd like to do some book keeping in an AFTER handler, but I'm unable to get the path of the handler that previously matched. It always resolves to "*" within the AFTER handler.
This PR adds a new context method that solves the issue. I left the original method untouched for backwards compatibility.
> [core] Add ability to get handler path (excluding AFTER handlers)

- src/main/java/io/javalin/apibuilder/ApiBuilder.java
Allows HEAD methods to be used in Javalin routes
> Add HEAD method to ApiBuilder

- pom.xml
As discussed in #434, this pull request configures the Kotlin compiler to target Java 8 bytecode.
> Target Java 8 bytecode with Kotlin (fixes #434)

- src/main/java/io/javalin/EmbeddedJavalin.kt
- src/main/java/io/javalin/core/JavalinServlet.kt
- src/main/java/io/javalin/staticfiles/JettyResourceHandler.kt
- src/main/java/io/javalin/staticfiles/ResourceHandler.kt
`JettyResourceHandler` implementation does not fit my use case. I would like to be able to supply my own implementation for `JavalinServlet`.  
It would probably be a _cleaner_ solution if the entire `JettyResourceHandler` was moved behind an interface and adding a setter to the `Javalin` object. In my opinion that would be just overkill.
> Extendable static files

- src/main/java/io/javalin/apibuilder/ApiBuilder.java
- src/test/java/io/javalin/TestApiBuilder.kt
Hi Tipsy,
I thought I give it a try and make my first contribution. I hope I got the assumptions about the crud handler right.
I assumed the following intended use:
```java
crud("users/:user-id", new UserController());
crud("foo/users/:user-id", new UserController()); //was prev not working -> fixed now
```
I assumed the following use should lead to an exception:
```java
crud("/users", new UserController());
crud("/:user-id", new UserController());
crud("/foo/:user-id/bar", new UserController());
```
> fixed #480

- src/main/java/io/javalin/validation/JavalinValidation.kt
- src/main/java/io/javalin/validation/Validator.kt
- src/test/java/io/javalin/validation/TestValidation.kt
This checks this existence of a validator and the result of a validator separately.  This prevents the wrong error message if a registered validator returns null.  Fixes #535
This got a little awkward so let me know if this is the best way to handle it.  It looks like the issue is really only for Java applications.  The original implementation said a validator could only return non-null `Any` values.  So in Kotlin you could never get this issue since null types are strictly known at compile time.   However Java has no such language restriction.  So a Java validator could return null and Kotlin had no way of checking nullability so it allowed it.
In order to make the Kotlin compiler play nice with Java I had to switch the converter map to `Any?` and then separate the original elvis …
>  Handle validator throwing null

- src/main/java/io/javalin/Javalin.java
- src/main/java/io/javalin/core/JavalinServer.kt
If Javalin initializes a server but then fails to start, there will be a runaway thread that doesn't get shutdown.
This PR sets a variable indicating we initialized the server and should attempt to stop/kill it if we fail to start.
This relates to #492. You might want to tweak how this is implemented. Ultimately, a public variable seems unnecessary (and possibly confusing) but I had to do it this way because of packages.
> Stop runaway thread

- src/main/java/io/javalin/core/PathParser.kt
Replace the old implementation, which is based mostly on string manipulation, with a class based approach. This is required to avoid duplication in the "openApi" PR.
> [core] refactor path parser

- src/main/java/io/javalin/core/JavalinConfig.java
- src/main/java/io/javalin/core/util/CorsPlugin.kt
- src/main/java/io/javalin/core/util/RouteOverviewPlugin.kt
- src/main/java/io/javalin/plugin/openapi/JavalinOpenApi.kt
- src/main/java/io/javalin/plugin/openapi/OpenApiPlugin.kt
- src/test/java/io/javalin/TestConfiguration.kt
- src/test/java/io/javalin/examples/HelloWorldSwagger.java
- src/test/java/io/javalin/openapi/TestOpenApi.kt
- src/test/java/io/javalin/openapi/TestOpenApiAnnotations.kt
- src/test/java/io/javalin/openapi/TestOpenApiAnnotations_Java.java
- src/test/java/io/javalin/openapi/TestOpenApiUi.kt
- src/test/java/io/javalin/openapi/utils.kt
- src/test/java/io/javalin/routeoverview/VisualTest.java
- src/test/kotlin/io/javalin/examples/HelloWorldSwagger.kt
@tipsy This is the first PR of refactoring. I didn't want to include everything in one PR so it doesn't get too big.
In this PR I refactored
* CORS
* RouteOverview
* OpenApi
For the last two I removed the "enable*" method from the config. I think you should use the 'registerPlugin' method for these. Just for CORS I left the "enable*" method as this feels more like a core option. Please let me know your thoughts on this change.
> [core] refactor cors, route overview and openapi to new plugin system (#577)

- pom.xml
- src/main/java/io/javalin/core/util/OptionalDependency.kt
I just saw that there is still an older version of swagger-ui in use and so I updated the dependencies to the latest release. All tests are OK, this should be a drop-in replacement.
> Updated swagger-core and swagger-ui dependencies

- src/main/java/io/javalin/plugin/openapi/OpenApiPlugin.kt
I tested the OpenApiPlugin on a small project and I made the mistake of not configuring an endpoint for the schema, while enabling the swagger ui. The result is, that the swagger ui won't be displayed.
As I think this is an easy error to make, I added a warning so the user will be notified about this mistake.
Feel free to update the wording. We should also consider to change this to an error.
> [openapi] add a warning if an ui is configured without the schema endpoint

- src/main/java/io/javalin/core/util/RouteOverviewUtil.kt
- src/main/java/io/javalin/plugin/openapi/OpenApiHandler.kt
- src/main/java/io/javalin/plugin/openapi/annotations/AnnotationApi.kt
- src/main/java/io/javalin/plugin/openapi/annotations/AnnotationApiMapping.kt
- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedParameter.kt
- src/main/java/io/javalin/plugin/openapi/dsl/OpenApiDocumentation.kt
- src/main/java/io/javalin/plugin/openapi/dsl/openApiBuilderDsl.kt
- src/main/java/io/javalin/plugin/openapi/external/KotlinOpenApiDsl.kt
- src/main/java/io/javalin/plugin/openapi/ui/ReDocRenderer.kt
- src/main/java/io/javalin/plugin/openapi/ui/SwaggerRenderer.kt
- src/test/java/io/javalin/openapi/TestOpenApi.kt
- src/test/java/io/javalin/openapi/TestOpenApiAnnotations.kt
- src/test/java/io/javalin/openapi/json.kt
* I realised that the schema generation doesn't work correctly with nested objects, so I fixed that.
* The documentation included the path to the schema itself and the swagger ui. I don't think that they should be included in the api documentation. So I added the option to ignore specific handlers, to remove these paths.
* I added some openapi documentation to the RouteOverview
> [openapi] Fix problems with nested objects and add option to ignore endpoint

- src/main/java/io/javalin/core/util/RouteOverviewUtil.kt
- src/main/java/io/javalin/plugin/openapi/annotations/AnnotationApi.kt
- src/main/java/io/javalin/plugin/openapi/annotations/AnnotationApiMapping.kt
- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedContent.kt
- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedRequestBody.kt
- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedResponse.kt
- src/main/java/io/javalin/plugin/openapi/dsl/OpenApiDocumentation.kt
- src/test/java/io/javalin/examples/HelloWorldSwagger.java
- src/test/java/io/javalin/openapi/TestOpenApi.kt
- src/test/java/io/javalin/openapi/TestOpenApiAnnotations.kt
- src/test/java/io/javalin/openapi/TestOpenApiAnnotations_Java.java
- src/test/java/io/javalin/openapi/json.kt
@tipsy As discussed I updated the RequestBody Annotation api. I used the opportunity to provide a better abstraction for the `content` of a request or response. The updated API is a little bit more powerful. For details please check the updated tests.
> [openapi] update api for request body and content types

- src/main/java/io/javalin/plugin/openapi/JavalinOpenApi.kt
- src/main/java/io/javalin/plugin/openapi/OpenApiHandler.kt
- src/main/java/io/javalin/plugin/openapi/OpenApiOptions.kt
- src/main/java/io/javalin/plugin/openapi/dsl/extractDocumentation.kt
- src/main/java/io/javalin/plugin/openapi/dsl/openApiBuilderDsl.kt
- src/test/java/io/javalin/openapi/TestOpenApi.kt
- src/test/java/io/javalin/openapi/json.kt
- src/test/kotlin/io/javalin/examples/HelloWorldSwagger.kt
The `default` option should be used to set responses that are in every request (like errors). Previously you could only configure it by manually defining the swagger definition. I updated the api so it works like the other dsl endpoints.
> [openapi] simplify default operator

- src/main/java/io/javalin/plugin/openapi/external/KotlinOpenApiDsl.kt
adding default handler for 'map' type using Swagger's MapSchema, should simplify for cases where the returnType is plainly map and not a POJO.
> [openapi] adding 'map' to the default schemes handler

- src/main/java/io/javalin/plugin/openapi/OpenApiOptions.kt
Revert the last PR, because anonymous lambdas in Java won't work anymore.
> Revert "[openapi] add constructor for `Supplier` in options (#619)"

- src/main/java/io/javalin/plugin/openapi/OpenApiHandler.kt
- src/test/java/io/javalin/openapi/TestOpenApi.kt
Allow cross-origin GET requests for the generated OpenApi schema. This will allow tools such as swagger-ui to render the schema remotely.
> [openapi] Support cross-origin requests for schema

- src/main/java/io/javalin/core/validation/Validator.kt
- src/test/java/io/javalin/TestValidation.kt
Closes #637 
This PR adds the ability have nullable typed query params.
```
val myThing: MyThing? = context
.queryParam<MyThing>("my_thing")
.getOrNull()
```
> allow queryParams to optionally be null

- src/main/java/io/javalin/plugin/metrics/MicrometerPlugin.kt
This change allows the `MicrometerPlugin` to be configured with a `MeterRegistry` making it easier to use. 
Currently the plugin can only be configured by providing a `CompositeMeterRegistry` rather than the super-type [`MeterRegistry`](https://www.javadoc.io/doc/io.micrometer/micrometer-core/1.2.0). 
Unless a user already has a `CompositeMeterRegistry`, they need to wrap a `MeterRegistry` in one, which is inconvenient. 
Additionally, `JettyStatisticsMetrics#monitor` and `JettyServerThreadPoolMetrics#bindTo` only require an instance of a `MeterRegistry` so it appears safe to start using the super-type (unless I have overlooked something?)
> [plugins] Configure metrics using a MeterRegistry

- src/main/java/io/javalin/http/Context.kt
- src/test/java/io/javalin/TestTemplates.kt
- src/test/resources/templates/pebble/test-empty-context-map.peb
This PR swaps the default `emptyMap()` model on the `Context.render` method with a `HashMap()`.
This fixes #644
> Fix for pebble's issue with immutable context maps

- src/main/java/io/javalin/core/validation/Validator.kt
- src/test/java/io/javalin/TestValidation.kt
This may fix #655, but confirmation is required from the reporter to make sure this bug is related to their own specific issue.
If a query param validator has rules and the value is null, you would get a 400.  This fix should correctly return the null value.
> fix getOrNull error when there are rules and value is null

- src/main/java/io/javalin/core/compression/Brotli.kt
- src/main/java/io/javalin/http/JavalinResponseWrapper.kt
Brotli.kt:
- Changed how output buffer padding is handled. Minimum size is now 2kb instead of 8kb, and the output buffer capacity is always twice the size of the input. This should avoid any further buffer overflows
- Added a length check to determine if compressed content is bigger than the original. If yes, we just send the original instead
- Setting of content-encoding header is now handled in this class.
> Fix Brotli Buffer

- pom.xml
- src/main/java/io/javalin/core/compression/Brotli.kt
- src/main/java/io/javalin/core/compression/CompressionStrategy.kt
- src/main/java/io/javalin/core/util/OptionalDependency.kt
- src/main/java/io/javalin/http/JavalinResponseWrapper.kt
- src/test/java/io/javalin/TestCompression.kt
pom.xml:
- jBrotli repository and dependency removed.
- Jvm-Brotli optional dependency added
Brotli.kt:
- Has been changed in line with the corresponding Gzip.kt class. A lot of unnecessary code has been removed.
CompressionStrategy.kt:
- Minor structural changes to tryLoadBrotli() method, to accommodate the fact jvm-brotli returns true/false when querying Brotli availability.
- Added optional dependency check to tryLoadBrotli()
OptionalDependency.kt
- Replaced jBrotli with Jvm-Brotli
JavalinResponseWrapper.kt:
- The buffer workaround and all corresponding variables have been removed. The Brotli code has been brought in line with that of Gzip.
- When initializing the compressor on first write, only one is initialized now. We no longer need both Gzip and Brotli initialized, since Brotli …
> [Compression] Remove jBrotli and Implement Jvm-Brotli

- src/main/java/io/javalin/core/util/RouteOverviewUtil.kt
Recently, I was on a ssh where I didn't have a web browser and the routes overview wasn't publicly accessible from the net. I had to `curl` requests to see what was going ond and to troubleshoot.
I added a small piece that shows the route overview in JSON format but couldn't find any place where to add a proper test.
> [core] Show route overview in JSON format for headless environments

- src/main/java/io/javalin/http/CachedRequestWrapper.kt
Update the log statement to be inline with the renamed function/variable (was `maxBodySizeForRequestCache` in Javalin v2).
> Fix log error message maxBodySizeForRequestCache -> requestCacheSize

- src/main/java/io/javalin/plugin/openapi/jackson/JacksonToJsonMapper.kt
- src/test/java/io/javalin/openapi/TestOpenApi.kt
- src/test/java/io/javalin/openapi/json.kt
Actual implementation of the OpenApi Security Scheme (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#securitySchemeObject) is incorrect. For example "apiKey" is incorrectly serialized in json (actual code produces "APIKEY"). Test also fixed.
> Fixed security scheme to specification

- pom.xml
- src/main/java/io/javalin/core/util/OptionalDependency.kt
The `groupId` changed from `com.mitchellbosecke` to `io.pebbletemplates`. I also updated the version and ran a simple manual test to confirm that it still works.
I also thought about updating [missingDependencyMessage](https://github.com/tipsy/javalin/blob/0c3732ca127b1632b7ba47b662cf1bd807f8d865/src/main/java/io/javalin/core/util/Util.kt#L56) to something like this (making it a bit more future proof, recommending to run with old dependencies is not great security wise):
```kotlin
internal fun missingDependencyMessage(dependency: OptionalDependency) = """|
|-------------------------------------------------------------------
|Missing dependency '${dependency.displayName}'. Add the dependency.
|
|pom.xml:
|<dependency>
|    <groupId>${dependency.groupId}</groupId>
| …
```
> Fix pebble maven coordinates in dependency suggestion

- src/main/java/io/javalin/core/util/Util.kt
As mentioned in https://github.com/tipsy/javalin/pull/767, this adds a hyperlink to the missing dependency message to allow developers to easily find the latest version (not every IDE has hints for this).
Example output:
```
-------------------------------------------------------------------
Missing dependency 'Jtwig'. Add the dependency.
pom.xml:
<dependency>
<groupId>org.jtwig</groupId>
<artifactId>jtwig-core</artifactId>
<version>5.87.0.RELEASE</version>
</dependency>
build.gradle:
compile "org.jtwig:jtwig-core:5.87.0.RELEASE"
Find the latest version here:
https://search.maven.org/search?q=g%3Aorg.jtwig+AND+a%3Ajtwig-core
-------------------------------------------------------------------
```
> Recommend latest version in missing dependency message

- src/main/java/io/javalin/Javalin.java
- src/main/java/io/javalin/core/JavalinServer.kt
- src/test/java/io/javalin/TestCustomJetty.kt
We often want to do this when running in docker and this makes this easier to do than what we need to do currently.
This means to set the bind host we can do `host("0.0.0.0")` like below:
```java
final Javalin app = Javalin.create(config -> {
...
}
);
app.host("0.0.0.0").start(8090);
```
---------------------
Rather than (what we currently do in java):
```java
int port = Integer.parseInt(System.getProperty("PORT", "8090"));
org.eclipse.jetty.server.Server server = new org.eclipse.jetty.server.Server();
ServerConnector connector = new ServerConnector(server);
connector.setHost("0.0.0.0");
connector.setPort(port);
server.setConnectors(new ServerConnector[]{connector});
final Javalin app = Javalin.create(config -> {
...
config.server(()-> server);
}
);
```
> Add the ability to set the bind host IP (like "0.0.0.0")

- src/main/java/io/javalin/plugin/openapi/annotations/AnnotationApi.kt
- src/main/java/io/javalin/plugin/openapi/annotations/AnnotationApiMapping.kt
- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedContent.kt
- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedRequestBody.kt
- src/main/java/io/javalin/plugin/openapi/dsl/OpenApiDocumentation.kt
- src/main/java/io/javalin/plugin/openapi/external/KotlinOpenApiDsl.kt
- src/test/java/io/javalin/openapi/TestOpenApi.kt
- src/test/java/io/javalin/openapi/TestOpenApiAnnotations.kt
- src/test/java/io/javalin/openapi/json.kt
**Describe the feature**
PR to add support for https://github.com/tipsy/javalin/issues/817
```
@OpenApi(composedRequestBody = @OpenApiComposedRequestBody(
anyOf = {
Address.class,
User.class,
}
)
)
```
should compile to json:
```
"requestBody" : {
"content" : {
"application/json" : {
"schema" : {
"anyOf" : [ {
"$ref" : "#/components/schemas/Address"
}, {
"$ref" : "#/components/schemas/User"
} ]
}
}
}
}
```
**Another minor changes**
Added more primitive wrappers (Double, Float, Boolean) to nonRefTypes and to findScheme
https://github.com/sealedtx/javalin/blob/b616f31c7ae9e97cdff329ff5a60644e894a4e5a/src/main/java/io/javalin/plugin/openapi/dsl/DocumentedContent.kt#L111-L112
```
val nonRefTypes = setOf(
...
Double::class.java,
java.lang.Double::class.java,
...
)
``` …
> openapi composed body feature (anyOf, oneOf)

- .github/workflows/main.yml
As discussed in #833, this change disables the informational download messages by setting the causing loggers log level to `warn`.
> [meta] Disable Maven dependency download messages

- src/main/java/io/javalin/plugin/openapi/annotations/AnnotationApi.kt
- src/main/java/io/javalin/plugin/openapi/annotations/AnnotationApiMapping.kt
- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedContent.kt
- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedResponse.kt
- src/main/java/io/javalin/plugin/openapi/dsl/OpenApiDocumentation.kt
- src/test/java/io/javalin/openapi/TestOpenApi.kt
- src/test/java/io/javalin/openapi/TestOpenApiAnnotations.kt
- src/test/java/io/javalin/openapi/json.kt
**Describe the feature**
Imporves support of composed scheme for openapi.
There was limitation in #825 for creating composed scheme of arrayed-elements.
#659 was not actually solved by #825, this PR adds support for responses with same status and group them to "oneOf" scheme.
> Improving support for composed scheme

- src/main/java/io/javalin/plugin/openapi/annotations/AnnotationApi.kt
- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedFormParameter.kt
- src/main/java/io/javalin/plugin/openapi/dsl/OpenApiDocumentation.kt
- src/main/java/io/javalin/plugin/openapi/dsl/openApiBuilderDsl.kt
- src/test/java/io/javalin/openapi/TestOpenApi.kt
- src/test/java/io/javalin/openapi/TestOpenApiAnnotations.kt
- src/test/java/io/javalin/openapi/json.kt
**Description:**
Fix for #859
`fileUploads` (like `formParam`) are now collected in a list and when we generate the docs both are taken into account to pick the correct content type and create a single entry in the `requestBody`.
**Test plan:**
Added new unit test case
**Outstanding issues:**
The `formParamBody` function is unchanged and will continue to use URL encoding even if there are also file uploads.
My current understanding of the code:
`formParamBody` applies changes as soon as it's called - this would cause issues if afterwords a `fileUpload` is added. We could defer this to later so that we know if there are file uploads as well.
But there is also the issue that both `fileUpload`and `formParamBody` offer the API to change the `requestBody`. Example:
```
OpenApiDocumentation() …
```
> Fixed Swagger doc for endpoints with file upload and from params

- src/main/java/io/javalin/plugin/openapi/dsl/OpenApiDocumentation.kt
- src/test/java/io/javalin/openapi/TestOpenApi.kt
- src/test/java/io/javalin/openapi/TestOpenApiAnnotations.kt
- src/test/java/io/javalin/openapi/json.kt
Follow up PR to #860 . 
`formParamBody` behaves a little bit different then `formParam`, as you provide a java class as a schema. The indented use case is to easily type more complex forms, that are not send as JSON.
It doesn't make sense to use the `uploadedFile` method in combination with `formParamBody`, as `formParamBody` contains the complete schema. If you want to add an file upload to this request, you would add a binary field to the class for the schema.
That's why I only added support to manually set the content type of the `formParamBody`, so you can use 'multipart/form-data' instead of 'application/x-www-form-urlencoded`.
> [openapi] support different content types in `formDataBody`

- pom.xml
This prepare the pom.xml to multi-module.
a PR exists since few months but many conflicts appear with the new release(s).
To ease the (re)work and limit the future conflicts
This PR:
- Add dependencies & plugins versions in `<properties>`, sorted (future jar updates are now grouped)
- Copy most of the dependencies from `<dependencies>` to `<dependencyManagement>` and adapt them (remove optional & scope)
- Keep the entries in `<dependencies>`, keep optional & scope, but remove the redundant `<version>` (most of the `<dependencies>` block will go to the javalin child pom.xml, except kotlin-lib dep)
> preparing multi-module

- javalin-bundle/pom.xml
- javalin-bundle/src/main/resources/logback.xml
- pom.xml
This add javalin-bundle module
a ready-to-go javalin dependency with Javalin, Logback and OpenAPI Plugin
a default logback config with console appender and info level is provided
original issue #933
> [bundle] add javalin-bundle module

- javalin/src/main/java/io/javalin/plugin/metrics/MicrometerPlugin.kt
- javalin/src/test/java/io/javalin/TestMicrometerPlugin.kt
- pom.xml
Hi there! I'm one of the Micrometer maintainers.
This PR upgrades to Micrometer 1.5.1 and makes several improvements to `MicrometerPlugin`.
Use the new Micrometer `TimedHandler`. Improve the plugin to ship a metric called `jetty.server.requests` with tags for `uri`, `exception`, `method`, `status`, and `outcome`. Much of the logic is around making the `uri` tag have meaning in the aggregate (represent the route and not the request path) and limit tag cardinality. It should look something like this:
I did find it kind of difficult to capture the exception for use as a tag in `TimedHandler` because:
- Javalin assumes there is only one exception handler per `Exception` class type
- Javalin always delegates to the closest matching handler by type. 
- Unless you manually set the status code to …
> Improve Micrometer plugin to tag requests by URI, outcome, status, etc.

- javalin/src/main/java/io/javalin/http/HttpResponseExceptionMapper.kt
- javalin/src/main/java/io/javalin/http/util/JsonEscapeUtil.kt
- javalin/src/test/java/io/javalin/TestExceptionMapper.kt
The jsonEscape function in TestExceptionMapper didn't
really do anything other than replace `"` with `\"`, which
doesn't handle things like newlines, backslashes or
any other characters that need to be escaped in JSON.
This patch uses the Jackson library function
JsonStringEncoder.quoteAsString to do the escaping.
> TestExceptionMapper: Do proper JSON escaping on title

- javalin/src/main/java/io/javalin/core/validation/BodyValidator.kt
- javalin/src/main/java/io/javalin/core/validation/Validator.kt
- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/test/java/io/javalin/TestValidation.kt
- retro-compatible with old version (non API breaking)
- Add method "isValid" to know if the data is valid
- Add method "hasError" to know if the data is not valid
- Add method "errors" to retrieve all error detected group by field name
- Add method check(String, Predicate, String) to add fieldName
**Code sample**
```kotlin
@JsonIgnoreProperties(ignoreUnknown = true)
data class Pojo(val firstName: String?, val email: String?)
fun test(ctx: Context): Context {
val p = ctx.bodyValidator<Pojo>()
.check("firstName", { it.firstName == null }, "This field is mandatory")
.check("firstName", { it.firstName?.length!! < 3}, "Must have at least 3 characters")
.check("firstName", { it.firstName?.length!! > 35}, "Cant be longer than 35 characters")
.check("email", { it.email == null}, "This field is …
```
> [javalin] Add methods to validate without exception

- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/main/java/io/javalin/websocket/WsContext.kt
Fixes issue #979 by annotating all reified methods which have a corresponding non-reified signature with `@JvmSynthetic`
The functions are already supposed to be for Kotlin users only, so I do not think it will cause problems.
Two cases of reified functions remain.
- `JavalinConfig.getPlugin()` in JavalinConfigExt.kt. This one is an extension function which will be available as `JavalinConfigExtKt.getPlugin(JavalinConfig)` which no one should be using. There is also no conflicting method here.
- `Context.bodyValidator()` in Context.kt. We do not have another method with the same name and signature that should be available. So we do not need to hide this reified method.
> Add missing JvmSynthetic annotations to reified methods. Fixes #979

- javalin-openapi/src/main/java/io/javalin/plugin/openapi/OpenApiOptions.kt
- javalin-openapi/src/main/java/io/javalin/plugin/openapi/dsl/DocumentedContent.kt
- javalin-openapi/src/main/java/io/javalin/plugin/openapi/dsl/OpenApiDocumentation.kt
- javalin/src/main/java/io/javalin/core/JavalinConfigExt.kt
- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/main/java/io/javalin/websocket/WsContext.kt
I missed `WsMessageContext#message()` the first time around (#981), so I marked all public inline methods with JvmSynthetic
> Add missing JvmSynthetic annotations to all public reified methods

- javalin/src/test/java/io/javalin/TestMultipartForms.kt
- javalin/src/test/java/io/javalin/testing/UploadInfo.kt
The new way enables the test file to have a different line ending compared to the OS.
Also remove the deprecated use of UploadedFile.contentLength, using size instead.
The two modified tests caused me some trouble locally as the test file has Linux style line (LF) endings on my Windows system causing the tests to fail. The new solution checks the resulting string for Windows style line endings (CRLF) and uses a different expected string compared to Linux/macOS.
This also fixes the scenario of a test file with Windows style line endings on a non Windows system.
> Remove OS specific line ending solution in TestMultipart

- javalin/src/main/java/io/javalin/http/util/ContextUtil.kt
- javalin/src/test/java/io/javalin/TestBodyReading.kt
Keys in x-www-form-urlencoded form params should also be %-decoded, according to specs
> Fix for properly decoding form param keys

- javalin/src/main/java/io/javalin/http/staticfiles/JettyResourceHandler.kt
- javalin/src/test/java/io/javalin/TestStaticFiles.kt
Allow for paths to static files, such as `/subdir` to be handled as `/subdir/`, which in turn allows for `/subdir/index.html` to be accessed via `/subdir`, `/subdir/` and `/subdir/index.html`.
Fixes #1002.
> Improve welcome file handling

- javalin/src/main/java/io/javalin/plugin/json/JavalinJackson.kt
- javalin/src/test/java/io/javalin/TestJson.kt
When a mapper is provided via JavalinJackson.configure(), we lack the ability to retain the settings of the default mapper
(namely, having the jackson-module-kotlin module registered by default, which can be surprising)
> [javalin] Expose factory method JavalinJackson.defaultObjectMapper

- javalin/src/main/java/io/javalin/plugin/rendering/template/JavalinJte.kt
- javalin/src/test/java/io/javalin/TestTemplates.kt
- pom.xml
Hey @tipsy, I finished HMTL support for jte sooner than expected. The context-sensitive output escaping works really good and is very fast too. I'm running my website in production with 0.8.0 and `ContentType.Html` for a week or so, that I'd consider the 0.8.0 version stable!
In this PR I updated the jte version to 0.8.0 and set `ContentType.Html` as default in `JavalinJte.kt`. I think it is a sane default and prevents users from nasty footguns (XSS attacks and the like).
Let me know what you think 😊
> Use jte 0.8.0, default engine uses ContentType.Html.

- javalin/pom.xml
- javalin/src/main/java/io/javalin/core/util/OptionalDependency.kt
- javalin/src/main/java/io/javalin/plugin/rendering/template/JavalinJte.kt
- javalin/src/test/java/io/javalin/TestTemplates.kt
- pom.xml
Hey @tipsy!
I finally considered jte stable enough to release a 1.0 version! I also built a small landing page for it with Javalin (https://jte.gg/).
Sorry about the jte tutorial delay, gonna sit down and write it the next days. It probably makes sense to publish it after the next Javalin version is out, right? Otherwise people won't have the extension and might be confused.
> Use jte 1.0.0.

- javalin/src/main/java/io/javalin/plugin/rendering/vue/JavalinVue.kt
There doesn't appear to be any valid usecases for fetching insecure CDN
content.
> [javalinvue] Use https instead of matching scheme for cdn resources

- javalin/src/main/java/io/javalin/plugin/rendering/vue/VueDependencyResolver.java
- javalin/src/test/java/io/javalin/TestJavalinVueResolution.java
- javalin/src/test/resources/vue/dependency-1-foo.vue
- javalin/src/test/resources/vue/dependency-1.vue
- javalin/src/test/resources/vue/dependency-123.vue
- javalin/src/test/resources/vue/view-number-dependency.vue
Currently there is a bug where components such as `<id-secure-wg2-login>` are resolved as `id-secure-wg`. This commit fixes this by updating the regex. Corresponding tests added.
> [VueDependencyResolver] Allow components with digits in name

- javalin/src/main/java/io/javalin/plugin/rendering/vue/VueDependencyResolver.java
- javalin/src/test/java/io/javalin/TestJavalinVueResolution.java
- javalin/src/test/resources/vue/view-multiline-dependency.vue
The components in `view-multiline-dependency.vue` would not have been picked up before this change.
Also allows for `Vue.component(` and `Vue.component (` (space before
parenthesis).
> Fix allow multiline tags in VueDependencyResolver

- javalin-openapi/src/main/java/io/javalin/plugin/openapi/jackson/JacksonToJsonMapper.kt
- javalin-openapi/src/main/java/io/javalin/plugin/openapi/jackson/JavalinModelResolver.kt
- pom.xml
The flag is excluded in default swagger object mapper.
Fixes #1079 - issues after updating to swagger 2.1.4
> Skipping exampleSetFlag on serialization

- javalin-openapi/src/main/java/io/javalin/plugin/openapi/external/KotlinOpenApiDsl.kt
- javalin-openapi/src/test/java/io/javalin/plugin/openapi/TestOpenApi.kt
- javalin-openapi/src/test/java/io/javalin/plugin/openapi/TestOpenApiAnnotations.kt
- javalin-openapi/src/test/java/io/javalin/plugin/openapi/json.kt
Resolves #1047 
Here the `Enum` type is being added to components because `isNonRefType()` returns `false` for `Enum`
https://github.com/tipsy/javalin/blob/1a32e62287292b14f8b62b411fc059ec27e5a867/javalin-openapi/src/main/java/io/javalin/plugin/openapi/dsl/DocumentedParameter.kt#L36-L40
But here in `findSchema` there is different implementation for enums - `getEnumSchema` - which does not allow to create ref schema, it simply returns `StringSchema` with enum values. That is why ref schema is not added to components.
https://github.com/tipsy/javalin/blob/1a32e62287292b14f8b62b411fc059ec27e5a867/javalin-openapi/src/main/java/io/javalin/plugin/openapi/external/KotlinOpenApiDsl.kt#L106-L109
Here later, again because `isNonRefType()` returns `false` for `Enum`, the code creates ref schema …
> OpenAPI: fix adding Enums to components (resolves #1047)

- javalin/src/main/java/io/javalin/core/PathParser.kt
- javalin/src/test/java/io/javalin/TestTrailingSlashes.kt
The current ignoreTrailingSlashes implementation was buggy : it changed how path are split and leave empty segments in the list.
This PR : 
- add Tests of ignoreTrailingSlashes=false : with tests from standard javalin TestRouting 
- don't change anymore how path are split to List&lt;Segment&gt;
- adapt the match regex to take account of trailing slashes or not
- pass the tests
> Fix ignoreTrailingSlashes

- javalin/src/main/java/io/javalin/core/JavalinConfig.java
- javalin/src/main/java/io/javalin/http/staticfiles/JettyResourceHandler.kt
- javalin/src/main/java/io/javalin/http/staticfiles/ResourceHandler.kt
- javalin/src/test/external/txt.txt
- javalin/src/test/java/io/javalin/TestStaticFiles.kt
- javalin/src/test/java/io/javalin/examples/HelloWorldStaticFiles_linked.java
Resolves #1086
Added possibility to set alias checks to serve static files. Because `ResourceHandler` was called manually it was impossible to attach context to enable jetty's alias checks. So I re-implemented `ResourceHandler.getResource()` to check aliases set by user in `StaticFileConfig` during configuring Javalin config.
**Example:**
```
Javalin.create(config -> {
// will serve successfully all aliased/linked files
config.addStaticFiles("src/test/external/", Location.EXTERNAL, Collections.singletonList(new ContextHandler.ApproveAliases()));
// will server only checked by custom rules aliased/linked files
config.addStaticFiles("src/test/external/", Location.EXTERNAL, Collections.singletonList(new MyAliasCheck()));
// won't server aliased/linked files …
```
> Serving static aliased files (resolves #1086)

- javalin-openapi/src/main/java/io/javalin/plugin/openapi/ui/ReDocRenderer.kt
- javalin-openapi/src/main/java/io/javalin/plugin/openapi/ui/RedocOptionsObject.kt
- javalin-openapi/src/main/java/io/javalin/plugin/openapi/ui/RedocOptionsTheme.kt
- javalin-openapi/src/test/java/io/javalin/examples/HelloWorldSwagger.java
- javalin-openapi/src/test/kotlin/io/javalin/examples/HelloWorldSwagger.kt
Redoc contains a list of customizable options in its options object (https://github.com/Redocly/redoc#redoc-options-object). This commit enables that customization inside Javalin's DSL.
For each type of object, a builder was created to ease Java's usage, as the language doesn't support default arguments yet.
An important point to verify here is that the Theme option, although configurable, won't work with the standalone version currently, due to a bug in Redoc itself (https://github.com/Redocly/redoc/issues/1248). If it gets fixed, the code from this commit will automatically work with it.
Closes #1097
> Add Redoc Options configuration

- javalin/src/main/java/io/javalin/Javalin.java
- javalin/src/main/java/io/javalin/apibuilder/ApiBuilder.java
So that Javalin instances can be created in parallel by multiple threads.
> ApiBuilder - replaced static fields with ThreadLocals

- javalin-openapi/src/main/java/io/javalin/plugin/openapi/OpenApiPlugin.kt
- javalin-openapi/src/test/kotlin/io/javalin/examples/HelloWorldMultiSwagger.kt
This is a small addition to the `OpenApiPlugin`, enabling devs to have multiple concurrent OpenApi specifications, as originally in #1108 
The addition has a rather simple approach: If `OpenApiOptions` differ in their path, they are added to be served concurrently, so now the `OpenApiPlugin`  constructor accepts a variable amount of options:
```kotlin
val app = Javalin.create {
val fullOpenApiOptions = OpenApiOptions(Info().version("1.0").description("My Application"))
.path("/swagger-docs")
.swagger(SwaggerOptions("/swagger").title("My Swagger Documentation"))
.reDoc(ReDocOptions("/redoc", RedocOptionsObject(
hideDownloadButton = true,
theme = RedocOptionsTheme(
spacingUnit = 10,
isTypographyOptimizeSpeed = true
)
)).title("My ReDoc Documentation"))
.defaultDocumentation { documentation …
```
> Extended OpenApiPlugin, to support multiple options

- javalin/src/main/java/io/javalin/core/PathParser.kt
- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/main/java/io/javalin/http/PathMatcher.kt
- javalin/src/main/java/io/javalin/http/util/ContextUtil.kt
- javalin/src/test/java/io/javalin/TestRouting.kt
After some discussion in #526, this will restore the `splat` and `splats` methods the the `Context`.
> restore splats to context

- javalin/src/main/java/io/javalin/core/util/OptionalDependency.kt
- pom.xml
@tipsy thanks for bumping to jte 1.4.0 👍 
I just bumped to jte 1.5.0, which adds some minor fixes and improvements: https://github.com/casid/jte/releases/tag/1.5.0
> Bump jte to version 1.5.0

- javalin/src/main/java/io/javalin/plugin/metrics/MicrometerPlugin.kt
- javalin/src/test/kotlin/io/javalin/plugin/metrics/MicrometerPluginTest.kt
This lets the micrometer plugin register the JettyConnectionMetrics after Javalin has started
> MicrometerPlugin registers connections after startup

- javalin/src/main/java/io/javalin/plugin/metrics/MicrometerPlugin.kt
- javalin/src/test/java/io/javalin/TestMicrometerPlugin.kt
- javalin/src/test/java/io/javalin/testing/HttpUtil.kt
Currently, the Micrometer plugin tags 3xx and 404 responses with the values `REDIRECTION` and `NOT_FOUND`, respectively. This PR adds configuration parameters on the plugin constructor to make it possible for the paths to requests like these to be tagged normally.
(In my case, the biggest motivator for this is for 304 responses generated via `config.autoGenerateEtags`)
> Optionally tagging 3xx and 404 responses in the Micrometer plugin

- CONTRIBUTING.md
- javalin/src/main/java/io/javalin/Javalin.java
- javalin/src/main/java/io/javalin/apibuilder/ApiBuilder.java
- javalin/src/main/java/io/javalin/core/JavalinConfig.java
- javalin/src/main/java/io/javalin/core/util/LogUtil.kt
- javalin/src/main/java/io/javalin/websocket/JavalinWsServlet.kt
- javalin/src/main/java/io/javalin/websocket/WsConnection.kt
- javalin/src/main/java/io/javalin/websocket/WsExceptionHandler.java
- javalin/src/main/java/io/javalin/websocket/WsHandlers.java
- javalin/src/main/java/io/javalin/websocket/WsPathMatcher.kt
- javalin/src/test/java/io/javalin/routeoverview/VisualTest.java
This PR follows up on https://github.com/tipsy/javalin/issues/1191#issuecomment-794137985
Besides the rename there are small documentation improvements and a pointless HashMap is removed from WsHandlerController.
> Rename WsHandlerController & WsHandler

- javalin/pom.xml
- javalin/src/main/java/io/javalin/core/util/OptionalDependency.kt
- javalin/src/main/java/io/javalin/plugin/rendering/JavalinRenderer.kt
- javalin/src/main/java/io/javalin/plugin/rendering/template/JavalinJte.kt
- javalin/src/test/java/io/javalin/TestTemplates.kt
- javalin/src/test/resources/templates/jte/multiple-params.kte
- javalin/src/test/resources/templates/jte/test.kte
- pom.xml
jte allows template expression in Kotlin instead of Java since [version 1.8.0](https://github.com/casid/jte/releases/tag/1.8.0), which would be a nice fit for Javalin.
See this issue for more details: https://github.com/tipsy/javalin/issues/1206
> Add support for kotlin templates

- pom.xml
Hello, just a little dependency bump for Jetty to resolve CVE-2021-28165
> bump Jetty in order to address CVE-2021-28165

- javalin/src/main/java/io/javalin/http/JavalinServlet.kt
- javalin/src/test/java/io/javalin/TestFuture.kt
> Handling exceptions thrown while writing the result stream on asynchronous requests.

- javalin-openapi/src/main/java/io/javalin/plugin/openapi/OpenApiHandler.kt
- javalin-openapi/src/main/java/io/javalin/plugin/openapi/OpenApiOptions.kt
- javalin-openapi/src/test/java/io/javalin/plugin/openapi/TestOpenApiIncludePath.kt
- javalin-openapi/src/test/kotlin/io/javalin/examples/HelloWorldMultiSwagger.kt
The aim of this pull request is to add an includePath option to the OpenAPI configuration.  If includedPaths are defined then the OpenAPI plugin will only include paths which match (and which are not explicitly excluded).  Effectively it is a "whitelist" as opposed to ignorePaths which are a "blacklist".
Note that, when doing this I noticed what I think is a bug in the OpenAPI plugin but I wasn't sure of the best way to resolve it.  Specifically, the logic being used to see whether a handler matches an included/excluded path uses PathParser.matches but this seems not to return the results you might expect.
For example, specifying an ignore path of "/users*" does not exclude /users/:id - this can be seen in the example HelloWorldMultiSwagger.kt which does exactly that.  The test for "items …
> Added in an option to set a list of explicitly included paths for the OpenAPI Plugin

- javalin/src/main/java/io/javalin/plugin/rendering/vue/JavalinVue.kt
- javalin/src/main/java/io/javalin/plugin/rendering/vue/VueComponent.kt
- javalin/src/main/java/io/javalin/plugin/rendering/vue/VueDependencyResolver.java
- javalin/src/test/java/io/javalin/TestJavalinVue.kt
- javalin/src/test/java/io/javalin/TestJavalinVueResolution.java
- javalin/src/test/resources/vue/dependency-one-3.vue
- javalin/src/test/resources/vue/dependency-two-3.vue
- javalin/src/test/resources/vue/test-component-3.vue
- javalin/src/test/resources/vue/view-one-3.vue
basically, this solves #1123  . After linting the vue docs and migration guide, the only part that actually effects us is that we have Instance-based components instead of global components and the fact that there is  a different place to inject extras instead of manipulating the Vue prototype. This is the initial implementation, and i've made sure nothing is broken from it. However, need to add more testing before pushing out.
@tipsy  a quick review before i continue work would be nice.
> Vue 3 Support

- javalin-openapi/pom.xml
- javalin-openapi/src/main/java/io/javalin/plugin/openapi/dsl/DocumentedResponse.kt
- javalin/src/main/java/io/javalin/http/HttpCode.kt
- javalin/src/test/java/io/javalin/http/HttpCodeTest.kt
- Adds new HttpCode class in javalin which can translate status codes to
messages.
- Excludes Jetty dependencies is javalin-openapi.
- Uses new HttpCode in DocumentedResponse
Fixes #1229
> Removes dependency on Jetty in javalin-openapi

- javalin-graphql/src/main/java/io/javalin/plugin/graphql/GraphQLHandler.kt
- javalin-graphql/src/main/java/io/javalin/plugin/graphql/graphql/GraphQLRun.kt
- javalin-graphql/src/test/kotlin/io/javalin/plugin/graphql/TestGraphQL.kt
- javalin-graphql/src/test/kotlin/io/javalin/plugin/graphql/helpers/QueryExample.kt
Currently the graphql plugin does not use a operation name which is provided in a graphql query resulting in an exeption if more than one query is sent by a client, for example by GraphiQL. This Pull request changes that.
> use operation name in graphql execution

- .github/workflows/main.yml
Upgrades both [actions/checkout](https://github.com/actions/checkout/blob/main/CHANGELOG.md) and [actions/setup-java](https://github.com/actions/setup-java/blob/main/docs/switching-to-v2.md) to v2. 
Also introduce caching for dependencies downloaded by Maven. According to the [docs at actions/cache](https://github.com/actions/cache#cache-limits) we have a budget of 5GB for cached files which do get overwritten should hit we the limit. 
Cached files older than one week are also deleted automatically.
The cache action configuration is a [textbook example from their documentation.](https://github.com/actions/cache/blob/main/examples.md#java---maven)
Fixes #1254
> [meta] Upgrade workflow steps and cache Maven deps (#1254)

- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/test/java/io/javalin/TestCookie.kt
- javalin/src/test/java/io/javalin/TestRequest.kt
- javalin/src/test/java/io/javalin/TestResponse.kt
This PR sets "/" as default path when removing cookies. 
Please see [issue 1257](https://github.com/tipsy/javalin/issues/1257) for details.
A new test class has been added as I could not see any existing test class where the test cases would fit.
> Set default path to root URL

- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/test/java/io/javalin/TestContextHandlerType.java
> [context] Expose HandlerType in Context (#1264)

- javalin-openapi/src/main/java/io/javalin/plugin/openapi/jackson/JavalinModelResolver.kt
- javalin-openapi/src/test/java/io/javalin/plugin/openapi/TestOpenApi.kt
I think that this if statement should probably just be deleted (or expanded to encompass the many other Date/Time types). However, this keeps current functionality unless a schema annotation is present, allowing users to override the many parameters available in the documentation.
> Fix schema annotation ignored on Instants

- javalin/src/main/java/io/javalin/core/util/Util.kt
- javalin/src/main/java/io/javalin/http/ExceptionMapper.kt
- javalin/src/main/java/io/javalin/http/JavalinResponseWrapper.kt
#1277 
I *think* this is the appropriate place to catch this exception. Since it's a regular TimeoutException, it might be useful in other places so we shouldn't hide it more broadly like we do with `isClientAbortException`'s handling of `EofException` in `Util.kt`.
```
2021-06-13 18:47:47.563 GMT ERROR io.javalin.Javalin - Exception occurred while servicing http-request
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:257)
at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:270)
at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:1045)
>>> at io.javalin.http.OutputStreamWrapper.write(JavalinResponseWrapper.kt:120)
at …
```
> Catch and ignore TimeoutException when writing a response

- README.md
The `compile` configuration has been deprecated and removed in Gradle
7.0. `implementation` configuration should be used instead.
> Update Gradle example to use implementation configuration

- javalin/src/main/java/io/javalin/core/util/ReflectionUtil.kt
By default `Class.forName` checks the calling classes class loader for the class, which is fine in most cases. However if a class has come from another classloader any attempt to use `parentClass` will fail since it will be called from the javalin class loader by default, which doesn't contain the class in question. To mitigate this, we pass the class loader of the class we are trying to get the parent for.
> Fix trying to find parent class in other class loaders

- javalin/src/main/java/io/javalin/http/Context.kt
In order to prevent new creation of a map, whenever a single value via
ctx.formParam*() or ctx.queryParam*() method is accessed, this commit
lazily intializes a map, which then gets used with any future access.
Closes #1322
> Load Context form/query parameters lazily into map

- javalin/src/main/java/io/javalin/jetty/JettyUtil.kt
#1277 
Following your suggestion of checking the cause's class name. I looked through our logs and every time we got this timeout it was a TimeoutException wrapped in an IOException, so I think it would be most precise to first check if the throwable is an IOException before checking the throwable's cause for TimeoutException.
> Fix Jetty TimeoutException detection to check a thrown IOException's cause

- javalin/src/main/java/io/javalin/core/routing/ParserState.kt
- javalin/src/main/java/io/javalin/core/routing/PathSegment.kt
- javalin/src/main/java/io/javalin/http/util/RedirectToLowercasePathPlugin.kt
- javalin/src/test/java/io/javalin/TestRouting.kt
- javalin/src/test/java/io/javalin/TestTrailingSlashes.kt
Still looking for a way to allow configuration on a per-path basis.
> Disable regex routing by default

- javalin/src/main/java/io/javalin/Javalin.java
That's my fault, introduced in #1351. I'm not quite sure how it happened as I didn't really touch this class during related PR.
> GH-1351 Remove unnecessary println call from constructor

- javalin/src/main/java/io/javalin/jetty/JettyPrecompressingResourceHandler.kt
- javalin/src/test/java/io/javalin/http/ContentTypeTest.kt
Fixes [bug](https://github.com/tipsy/javalin/issues/1361).
Added null check for checking the value of contentType, so java.lang.NullPointerException should not be raised.
So the file should be served even if content type isn't set.
> Fixes #1361

- javalin/src/main/java/io/javalin/core/validation/BodyValidator.kt
Added @NotNull to get method in BodyValidator to match Validator, and get rid of the possible NPE warning in IntelliJ, per Discord conversations with tipsy.
Tests passed locally, though it is just an annotation 😄
> [validation] Fix incorrect null warning in BodyValidator

- javalin-openapi/src/main/java/io/javalin/plugin/openapi/OpenApiHandler.kt
- javalin-openapi/src/main/java/io/javalin/plugin/openapi/jackson/JacksonToJsonMapper.kt
- javalin-openapi/src/test/java/io/javalin/plugin/openapi/TestOpenApi.kt
- javalin-openapi/src/test/java/io/javalin/plugin/openapi/TestOpenApiHandler.kt
- javalin/src/main/java/io/javalin/core/util/OptionalDependency.kt
- pom.xml
- openapi dependencies are now on the latest version
- removed reference to 1.x branch dep in validation
- added test to check for exampleSetFlag leakage
- use json mapper from swagger-core instead of a custom one
> [openapi] update openapi deps

- javalin-openapi/src/test/java/io/javalin/plugin/openapi/TestOpenApi.kt
As mentioned in Discord, this fixes a small error in the tests caused by #1381  .
> [openapi] Fixing the Instants as Timestamps test

- javalin/src/main/java/io/javalin/http/sse/Emitter.kt
> Each notification is sent as a block of text terminated by a pair of newlines.
> Fix SSE terminator

- javalin/src/main/java/io/javalin/core/validation/BaseValidator.kt
Change ValidationException to extend RuntimeException to match other response exceptions and eliminate errors when trying to catch them.
e.g.:
```
io.javalin.core.validation.ValidationException is never thrown in body of corresponding try statement 
```
> [validation] change ValidationException to extend RuntimeException

- javalin/src/main/java/io/javalin/http/JavalinResponseWrapper.kt
Just to note, I haven't managed to test this fix on 4.x as I only use 3.x!
> [core] Ensure LeveledGzipStream is properly closed

- javalin-osgi/README.md
- javalin-osgi/pom.xml
- pom.xml
As discussed at: https://github.com/tipsy/javalin/issues/1375
Testing with out OSGi enabled application been performed to ensure that newly introduced module `javalin-osgi` works as expected.
> Enable OSGi bundle packaging for Javalin

- javalin/src/main/java/io/javalin/core/util/OptionalDependency.kt
- pom.xml
This brings some 1.11.x bugfixes and faster hot reload of jte templates (https://github.com/casid/jte/releases/tag/1.12.0).
> Bump jte to version 1.12.0

- javalin/src/main/java/io/javalin/Javalin.java
- javalin/src/main/java/io/javalin/core/event/EventListener.java
- javalin/src/main/java/io/javalin/core/event/EventManager.kt
- javalin/src/test/java/io/javalin/TestLifecycleEvents.kt
Hi Tipsy. 
Resolves #1442. Tried to maintain your code style. If merged, the [docs](https://javalin.io/documentation#lifecycle-events) need updating. Let me know your thoughts. Note: this changes the contract for `stop()` because it now throws, as it should have originally.
Thanks.
> Add a "server stop failed" lifecycle event

- javalin/src/main/java/io/javalin/http/util/MultipartUtil.kt
- javalin/src/test/java/io/javalin/TestMultipartForms.kt
Fix for issues mentioned in https://github.com/tipsy/javalin/issues/1045 (uploading large files bloats JVM heap).
**Issue breakdown**
On each access to `uploadedFiles` methods, underlying `MultipartUtil` calls `preUploadFunction`. Under the hood it executes:
```java
req.setAttribute("org.eclipse.jetty.multipartConfig", MultipartConfigElement(System.getProperty("java.io.tmpdir")))
```
which in the long form looks something like this
```java
req.setAttribute("org.eclipse.jetty.multipartConfig", MultipartConfigElement(System.getProperty("java.io.tmpdir"), -1, -1, 0))
```
In your discussions with @Mynameisbt you were incorrect in assumption that `MultipartConfigElement`'s `fileSizeThreshold`, when set to `0`, always caches to disk. 
Unfortunately this is not the case and `0` actually disables …
> 1045: Fix for multipart form disk caching

- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/test/java/io/javalin/TestRequest.kt
When retrieving session attributes via `ctx.sessionAttribute()` there is
no requirement to create a session on retrieval - as opposed to setting
an attribute.
Closes #1470
> Ensure retrieving session attributes does not create a session

- javalin/src/main/java/io/javalin/core/util/Header.kt
- javalin/src/main/java/io/javalin/http/sse/SseHandler.kt
When proxied through nginx, server sent events currently have a delay of about 3 seconds.
After some trial and error I found this post: https://serverfault.com/a/801629
Setting the response header `X-Accel-Buffering=no` removes this delay. As mentioned in the article, it is recommended to set this header in the application, so buffering is only disabled for SSE requests and not all requests.
Currently, there is no mechanism to customize the SSE response headers. For now, I've hacked the SseHandler class in my application as a workaround.
This PR does the same as my class hack and simply sets `X-Accel-Buffering=no` in SseHandler.kt.
@tipsy what do you think to add this header by default? It doesn't cause much overhead and should be helpful for other users with an nginx proxy.
> Prevent SSE Buffering with nginx

- .github/workflows/main.yml
Java 18 has been release a few days ago, might be a good idea to run Javalin tests against it. I've added it as a 4th target, so we're declaring support for all LTS versions + the latest one. Sounds like a fair policy.
> [github] Add Java 18 to actions workflow

- javalin/src/test/java/io/javalin/TestWebBrowser.kt
Let's just don't use devtools by specifying random port explicitly
References:
* https://bugs.chromium.org/p/chromedriver/issues/detail?id=2473
> GH-1488 Disable lookup for DevToolsActivePort file

- javalin/src/main/java/io/javalin/core/util/OptionalDependency.kt
- pom.xml
Fix Issue 1524 (CVE-2018-25031) by upgrading Swagger UI version to `4.10.3`.
> Upgrade Swagger UI version to 4.10.3

- javalin/src/main/java/io/javalin/Javalin.java
- javalin/src/main/java/io/javalin/http/sse/SseHandler.kt
- javalin/src/test/java/io/javalin/TestSse.kt
Changes:
1. I've added `Javalin.sse` with `SseHandler` (also lambda) to Javalin class as it feels strange that I'd need to use `.get()` to do that. It's also a part of change associated to the optional `async timeout` set per each handler. 
I can revert this, but we'd need to use `.get` instead of `.sse` in tests to explicitly provide custom timeout.
3. SseHandler has now dedicated (optional) timeout value, so people can provide custom timeouts explicitly for handler rather than some magic tricks like it was before with e.g. after handler like it was in the test scenarios.
4. New SseHandler constructor is backwards compatibile due to @JvmOverloads flag.
5. SseHandler uses stub future instance to properly notify servlet about request state
6. Replaced global `shortTimeoutServer()` with …
> GH-1532 Adapt SseHandler to reimplemented servlet

- javalin/src/main/java/io/javalin/http/ExceptionMapper.kt
Updates `ExceptionMapper` to "unwrap" `CompletionException` so that it detects `EofException` and `TimeoutException` when using `ctx.future`.
The new line looks a bit long to me but not sure what the right formatting should be (reformatting in IntelliJ changed a heap of other formatting so my settings must be different somehow).
And there wasn't a test for the existing suppression of EofException that I could see so wasn't sure how to add one (first foray into this codebase and I'm not a Kotlin dev...).
closes #1544
> [logging] Avoid logging EofException and TimeoutException thrown by async responses

- javalin/src/main/java/io/javalin/http/JavalinServletHandler.kt
- javalin/src/main/java/io/javalin/http/sse/SseHandler.kt
- javalin/src/test/java/io/javalin/TestFuture.kt
- javalin/src/test/java/io/javalin/TestSse.kt
Associated with #1559
Pros:
* Well... it's still better than some kind of a manual check based on yet another global variable
* Blocks Javalin's handler servlet processing, so in general it's up to the user to close it
Cons: 
* ~It won't call finishResponse(), because AsyncListener behaves differently than regular execution state and it may result in lack of data passed to the final output right before the call, because listener has priority over http thread managed by Jetty. AsyncEvent provides some request/response, maybe we could somehow try to write here? idk~ I think it works like it was before seeing the impl of `AsyncContext#complete()`.
* A few arguments on Discord I still hold against introducing such change
In 5.x it should be removed anyway imo. Also, I've used the old approach …
> [core] Hot-fix proposal for manual usage of ctx.req.startAsync() 

- javalin/src/main/java/io/javalin/websocket/WsContext.kt
This PR adds a sendPing method to WsContext. This is the first PR to fix the problems mentioned in #1567.
Maybe we should add some tests, but pings are hard to test, as they only prevent timeouts which are sometimes OS or infrastructure dependent. As this is a simple method, maybe tests aren't actually necessary I think.
> [websocket] Add sendPing() method

- .github/workflows/publish-snapshots.yml
Syncing my fork causes a github action failure as my fork (rightfully) does not have the credentials.
This change limits the job to only run on the main repository.
Ref: https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution
> Limit Snapshot Job to the main repository

- javalin-testtools/src/test/java/io/javalin/testtools/JavaApp.java
- javalin-testtools/src/test/kotlin/io/javalin/testtools/KotlinApp.kt
- javalin/src/main/java/io/javalin/core/JavalinConfig.java
- javalin/src/main/java/io/javalin/core/PathParser.kt
- javalin/src/main/java/io/javalin/core/routing/RoutingRegexes.kt
- javalin/src/main/java/io/javalin/http/JavalinServlet.kt
- javalin/src/main/java/io/javalin/http/PathMatcher.kt
- javalin/src/main/java/io/javalin/http/util/RedirectToLowercasePathPlugin.kt
- javalin/src/main/java/io/javalin/jetty/JavalinJettyServlet.kt
- javalin/src/main/java/io/javalin/websocket/WsPathMatcher.kt
- javalin/src/test/java/io/javalin/TestMultipleSlashes.kt
- javalin/src/test/java/io/javalin/TestRouting.kt
- javalin/src/test/java/io/javalin/TestTrailingSlashes.kt
This change replaces all slashes in the regex construction with a matching equivalent accepting multiple slashes.
As I did not want to pass another boolean to the path parser, I modified the path parser to accept the JavalinConfig object.
I introduced some extra options objects to clarify what is actually needed from the config object. 
Last but not least are a ton of tests to verify the new behaviour.
Looking forward to feedback. :)
fixes #1528
> New config option treatMultipleSlashesAsSingleSlash - fixes #1528

- javalin/src/main/java/io/javalin/websocket/WsAutomaticPing.kt
- javalin/src/main/java/io/javalin/websocket/WsConnection.kt
- javalin/src/main/java/io/javalin/websocket/WsContext.kt
This refers to issue #1567 and adds methods for enabling & disabling automatic websocket pings.
I'm not entirely sure on how synchronization works with the used methods, to we need a mutex or similar? Is there a race somewhere in the code if two threads call enableAutomaticPings/disableAutomaticPings at the same time? Is that even possible? 
Maybe some sort of locking mechanism is required, but as a first prototype this patch does seem to work.
> [websocket] Add enableAutomaticPings & disableAutomaticPings

- javalin-testtools/src/main/java/io/javalin/testtools/HttpClient.kt
- javalin-testtools/src/main/java/io/javalin/testtools/JavalinTest.kt
- javalin-testtools/src/test/java/io/javalin/testtools/JavaTest.java
- javalin-testtools/src/test/kotlin/io/javalin/testtools/KotlinTest.kt
Implements https://github.com/javalin/javalin/issues/1582
@tipsy I decided to go for exposing `OkHttpClient` as it is much easier and fulfils my needs (currently `HttpClient` is coupled not only to `OkHttpClient` class but also `okhttp3.Request`- providing some abstraction over building request (e.g. adding header) looks like a overkill for me).
You also asked for making `JavalinTest` instantiable, I will do that in next PR :)
Signed-off-by: Mikolaj Matuszewski <mikolaj.matuszewski@digitalnewagency.com>
> Expose OkHttpClient via TestConfig

- javalin/src/main/java/io/javalin/http/JavalinServletHandler.kt
- javalin/src/main/java/io/javalin/http/sse/SseHandler.kt
- javalin/src/test/java/io/javalin/TestFuture.kt
- javalin/src/test/java/io/javalin/TestSse.kt
The hot-fix was meant to be removed in Javalin 5.x, having this fix we can start working on things like `ctx.async {}` proposal / sse reimplementation on top of threadpools etc. (#1517)
> [core] Remove hot-fix for backwards compatibility of `ctx.req.startAsync()` from Javalin 4.x

- javalin/src/main/java/io/javalin/core/JavalinConfig.java
- javalin/src/main/java/io/javalin/core/JavalinConfigExt.kt
- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/main/java/io/javalin/http/JavalinServletHandler.kt
- javalin/src/main/java/io/javalin/http/sse/Emitter.kt
- javalin/src/main/java/io/javalin/http/sse/SseClient.kt
- javalin/src/main/java/io/javalin/http/sse/SseHandler.kt
- javalin/src/test/java/io/javalin/TestAsync.kt
- javalin/src/test/java/io/javalin/TestSse.kt
Benefits:
* Officially supported way to delegate logic to async contex without a need to wrap it manually with a stub future
* Uses cached execturor service by default, so most users should be happy with it - in case some specific task there's an option to provide a custom one
* Properly handles and emits exceptions from task to servlet
* Supports Jetty-free timeouts, so we can enforce timeout and register timeout listener that is still able to write to context just like the handler
* `ctx.async` also returns future, so user also can listen for completion (**but can't modify context**)
* For SSE:
* All SSE connections are by default running in standalone executor, so we're not blocking Jetty's http thread by long-living connectins
* (Change in behaviour) We don't have to call …
> [context] Support async task delegation through `Context.async()` method

- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/test/java/io/javalin/TestFuture.kt
`resultStream()` does not properly check future status before an attempt to get the value
Found in #1591
> [context] Fix `Context.resultStream()`

- javalin/src/main/java/io/javalin/plugin/RedirectToLowercasePathPlugin.kt
- javalin/src/test/java/io/javalin/TestRedirectToLowercasePathPlugin.kt
This is only applicable to "complex" segments as defined by `PathSegment.MultipleSegments`.
This is the bug I found while looking at @dzikoysk 's refactor but it is actually a bug I created while creating the newer parser a while back.
> Avoid endless redirects when using RedirectToLowercasePathPlugin.kt

- javalin-testtools/src/test/java/io/javalin/testtools/JavaTest.java
- javalin-testtools/src/test/kotlin/io/javalin/testtools/KotlinTest.kt
Related to https://github.com/tipsy/javalin/pull/1565
Adds test cases to verify the behaviour of the exception handling.
Looking for a way to test the added logging behaviour in [PR 1565](https://github.com/tipsy/javalin/pull/1565): https://github.com/tipsy/javalin/pull/1566/files#diff-8213d57a28ef5ab05d803ccc0057eee4f193bcdafd136d0f57c31db7cdaca044R127
Any ideas?
> [testing] Add test cases for exception handling in JavalinTest

- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/main/java/io/javalin/http/JavalinServletHandler.kt
- javalin/src/main/java/io/javalin/util/FutureUtil.kt
- javalin/src/test/java/io/javalin/TestAsync.kt
- javalin/src/test/java/io/javalin/testing/HttpUtil.kt
* #1603
TL;DR we were letting user to set multiple futures and we didn't really care which one ended up in a `Result` - all we cared about was to properly handle state we found by atomic get & update of user's result. This PR will extend protection of user's logic by exposing a thread-safe possibility to launch async task. With such change, the `ctx.future()` & `ctx.async` should be always prioritized over other methods to spawn and handle async contex due to guarantee of proper execution.
> [core] Support a possibility to safely queue future

- javalin/src/main/java/io/javalin/apibuilder/ApiBuilder.java
- javalin/src/test/java/io/javalin/TestApiBuilder.kt
> Default path for Before/After handlers doesn't require trailing slashes

- pom.xml
This fixes certain tests not being executed by Maven.
Concrete example: TestFuture.kt
The two root tests are not executed by Maven without this change.
You can check for successful application of this fix by looking at the raw action logs and searching for `TestFuture`
Two tests should be shown as run, something similar to this:
```
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.032 s - in io.javalin.TestFuture
```
See also this JUnit5 issue: https://github.com/junit-team/junit5/issues/1377
> Override default excludes in maven-surefire-plugin config

- pom.xml
I forgot about it, but by default Kotlin does not generate Java-compatible default methods in interfaces, so we want to force this to keep proper interop & API consistency
> [build] Tell Kotlin compiler to generate default methods

- javalin/src/main/java/io/javalin/http/servlet/JavalinServlet.kt
- javalin/src/main/java/io/javalin/http/servlet/JavalinServletContext.kt
We don't need to use Lazy anymore due to some cleanups in servlet handling we've made during the latest servlet rewrite
> [servlet] Replace `Lazy<CompletableFuture>` with `Supplier<CompletableFuture>`

- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/main/java/io/javalin/http/Handler.java
- javalin/src/main/java/io/javalin/http/servlet/JavalinServlet.kt
- javalin/src/main/java/io/javalin/http/servlet/JavalinServletContext.kt
- javalin/src/main/java/io/javalin/plugin/bundled/DevLoggerPlugin.kt
- javalin/src/test/java/io/javalin/TestAccessManager.kt
- javalin/src/test/java/io/javalin/TestApiBuilder.kt
- javalin/src/test/java/io/javalin/TestFuture.kt
- javalin/src/test/java/io/javalin/TestLogging.kt
- javalin/src/test/java/io/javalin/TestResponse.kt
- javalin/src/test/java/io/javalin/TestRouting.kt
* #1659
Why I don't think it is a good idea to remove `resultStream()`:
- It's the root value that determines if context contains response or not -> So we can e.g. determine if response has been written by simply checking if `ctx.resultStream() == null`
- It's faster than `ctx.result()` because `ctx.result()` will try to read and convert whole stream to string - it's good to mention that not all responses are human readable context, so this method is pretty useless for any kind of media type
- It's inconsistent, why do we offer `ctx.result()` if we're not offering `ctx.resultStream()`, I'd rather expose `resultStream` than `result` as it just provides more possibilities to do sth with result in general
- Exposing `resultStream` only as a field has also some disadvantages:
- Internal …
> [context] Restore `ctx.resultStream()`

- javalin/src/main/java/io/javalin/util/OptionalDependency.kt
Use more popular Gradle format for defining dependency and support Kotlin DSL as well using kts compatible syntax
> [util] Update `missingDependencyMessage` message

- javalin/src/main/java/io/javalin/Javalin.java
- javalin/src/test/java/io/javalin/staticfiles/TestStaticFiles.kt
Inspired by some discussion on the Javalin Discord server: 
This PR add a new method for Javalin instances called `updateConfig` which fulfills a similiar role to the existing `create(Consumer)` function except that the new method is an instacne method and not a static method.
The testcase is inspired by the real world use case to add static files dynamically after creation of the instance.
Do note that I did not fix the issue for adding static files after server start. 
You currently have to do something like this after adding your files if you want to add static files after starting Javalin:
```kotlin
val app = Javalin.create().start()
app.updateConfig {
it.staticFiles.add("/assets", Location.CLASSPATH)
it.pvt.resourceHandler?.init(mapOf("server" to javalin.cfg.pvt.server))
}
```
> Add Javalin#updateConfig to allow config updates after creation

- javalin/src/main/java/io/javalin/util/OptionalDependency.kt
This is a tiny thing I noticed today: The slf4j-simple version that is currently suggested in the console if no slf4j provider can be found is incompatible with the slf4j-api version in use. I.e. if you add this specific version you'll get another warning that it is too old.
```
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:.../slf4j-simple-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```
> Update suggested slf4j-simple version

- javalin/src/main/java/io/javalin/http/HttpStatus.kt
Hello,
I'm working on a Java project and noticed the `HttpStatus.forStatus` method is missing. I added the `@JvmStatic` so the method is available in Java.
> Expose HttpStatus.forStatus to Java

- .github/ISSUE_TEMPLATE/1_Bug_report.md
- .github/ISSUE_TEMPLATE/2_Feature_request.md
- .github/ISSUE_TEMPLATE/3_Question.md
- .github/ISSUE_TEMPLATE/config.yml
Add this when clicking "New issue":
And automatically add label when creating issues
> Add auto labeling for issues and links to documentation & discord

- javalin/src/main/java/io/javalin/jetty/JettyResourceHandler.kt
- javalin/src/test/java/io/javalin/staticfiles/TestStaticDirectorySlash.kt
Fixes #1712
When setting `staticFiles.precompress = true;` javalin fails to serve the index.html file in directory requests.
> GH-1712 Static files handler 404s Welcome Files with `precompress` enabled

- javalin-testtools/src/main/java/io/javalin/testtools/HttpClient.kt
I Noticed a strange behavior when running tests in CI, where the test is much slower because its resolving each request to localhost. While this might be an issue thats only on my setup, we will always be using 127.0.0.1 anyway, so this shouldn't break anything
> update testtools to use localhost to skip resolution

- javalin/src/main/java/io/javalin/jetty/JettyUtil.kt
- javalin/src/main/java/io/javalin/util/ConcurrencyUtil.kt
I'd like to use `ConcurrencyUtil.jettyThreadPool` to setup custom thread-pool with loom support, but currently thread-pool limits are hard-coded.
> [utils] Expose `minThreads` & `maxThreads` in `ConcurrencyUtil#jettyThreadPool` method

- javalin/src/main/java/io/javalin/jetty/JettyUtil.kt
This is the simplest possible solution for #1740 - making the warning about not having started Javalin a "startup" message so it can be suppressed with `JavalinLogger.startupInfo = false`. Downside is it still creates a useless thread and you have to give up all the startup messages to suppress it, but this would work for our use case fine.
closes #1740
> [logging] Categorize created but never started message as a startup message

- .github/workflows/main.yml
We're getting a lot of deprecation warnings on builds, this should fix that.
>![image](https://user-images.githubusercontent.com/23284823/202440316-9136891e-503a-473d-a4ad-5ab0be220cff.png)
> Bump actions version

- javalin/src/main/java/io/javalin/config/FileUploadConfig.kt
- javalin/src/main/java/io/javalin/config/JavalinConfig.kt
- javalin/src/main/java/io/javalin/config/JettyConfig.kt
- javalin/src/main/java/io/javalin/config/MultipartConfig.kt
- javalin/src/main/java/io/javalin/http/util/MultipartUtil.kt
- javalin/src/test/java/io/javalin/TestMultipartForms.kt
I've done it the way that was discussed on the issue, whereby the user can set each parameter separately rather than via a single function with defaults.  There are a couple of things I'm not convinced about
I've done it the way discussed in the issue, where the user can set each attribute separately, but to me this has significant downsides solely to allow people to avoid static multipliers. Specifically, with a single function, we can construct a fully formed multipart config element at that point and set the preUploadFunction.  This means we don't need to instantiate one on every upload but can simply use a cached version.  
By allowing the user to set each parameter independently (particularly since they can then call updateConfig) we don't know when they are finished so at the moment …
> Ability to configure multipart upload through settings

- javalin/src/main/java/io/javalin/http/sse/Emitter.kt
- javalin/src/test/java/io/javalin/TestSse.kt
Each line of data in an SSE message must be prefixed with `data: `, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format) and the [spec](https://html.spec.whatwg.org/multipage/server-sent-events.html#dispatchMessage).
Clients are responsible for joining adjacent `data: ` lines using a newline character.
Fixes #1774.
> [sse] Prefix each line with `data: `

- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/test/java/io/javalin/TestJson.kt
> [context] Simplify usage of reified `Context#jsonAsType` by utilizing generic type in parameter

- pom.xml
Enables platforms not supported by conscrypt to implement the default Security Provider present in the JVM. (Such as Apple Silicon)
Currently used by javalin-ssl
> Add `jetty-alpn-java-server` to BOM

- javalin/src/main/java/io/javalin/http/HttpResponseException.kt
Nice-to-have enhancement for those utility wrappers, so I can do sth like:
```kotlin
class InvalidCredentialsResponse : UnauthorizedResponse("Invalid credentials")
```
Instead of:
```kotlin
class InvalidCredentialsResponse : HttpResponseException(UNAUTHORIZED, "Invalid credentials")
```
> [utils] Open access to all utility `HttpResponseException`-based wrappers

- javalin-testtools/src/main/java/io/javalin/testtools/TestTool.kt
It's kinda annoying to repeat `TestConfig` setup through several tests, so I think it might be a good idea to move those values to global wrapper.
> [testtools] Move `TestConfig` defaults to standalone configurable global wrapper

- javalin/src/main/java/io/javalin/http/Context.kt
Extra asterisk is converted into a bullet point.
> [context] Fix typo in documentation

- javalin/src/main/java/io/javalin/routing/PathParser.kt
- javalin/src/test/java/io/javalin/TestRouting.kt
We already add a leading slash so we need to handle the case of a single slash separately.
fixes #1803
> Add special consideration for the root path. Fixes #1803

- javalin/src/main/java/io/javalin/routing/PathMatcher.kt
- javalin/src/test/java/io/javalin/routeoverview/TestRouteOverviewPlugin.kt
The old implementation just searched for stars as `entry.matches("*")` always returns false leading to only two matches out of 32.
> Fix RouteOverviewTest by actually iterating over all entries

- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/main/java/io/javalin/json/JavalinJackson.kt
- javalin/src/main/java/io/javalin/json/JsonMapper.kt
- javalin/src/test/java/io/javalin/TestJson.kt
This adds a `writeStream()` function to JsonMapper interface, a `writeJsonStream()` function to `Context`, and implements `writeStream()` in `JavalinJackson`.
> Implement JSON streaming in JavalinJackson

- javalin/src/main/java/io/javalin/json/JavalinGson.kt
- javalin/src/test/java/io/javalin/TestJson.kt
This implements writing JSON directly to an output stream from a `Stream<T>` using the Gson mapper.
> Implement writeToOutputStream for JavalinGson

- javalin/src/main/java/io/javalin/http/HttpResponseException.kt
- javalin/src/test/java/io/javalin/http/HttpResponseExceptionTest.kt
As discussed in #1811
Couple of talking points:
* wildcard importing `HttpStatus.*`
* not keeping `RedirectResponse`
* whether the test is actually useful
> Implement a HttpResponseException for all HttpStatus enum values

- javalin/src/main/java/io/javalin/http/servlet/JavalinServlet.kt
- javalin/src/main/java/io/javalin/http/util/AsyncUtil.kt
- javalin/src/test/java/io/javalin/TestFuture.kt
Resolves #1822 
This PR:
1. Makes it possible to use `asyncCtx` in `future` supplier
2. Disables global timeout for `async` requests (because they're using other timeout system)
> [async] Disable default timeout system for all async requests

- javalin/src/main/java/io/javalin/http/ContentType.kt
- javalin/src/main/java/io/javalin/http/staticfiles/StaticFileConfig.kt
- javalin/src/main/java/io/javalin/jetty/JettyResourceHandler.kt
- javalin/src/test/java/io/javalin/staticfiles/TestSinglePageMode.kt
- javalin/src/test/java/io/javalin/staticfiles/TestStaticFiles.kt
- javalin/src/test/resources/public/file.javalin
- javalin/src/test/resources/public/module.mjs
Had to change the extension value of `ContentType.APPLICATION_JS`, as we currently require unique extensions for each content type.
This does not affect using the content type in `Context.contentType()`
Similarly I switched everything over to `text/javascript` as a mimetype, so we stay in sync with Jetty.
Ref: javalin/javalin#1820
> Add mimeTypes option to staticFiles and switch to text/javascript

- javalin/src/main/java/io/javalin/http/servlet/JavalinServlet.kt
- javalin/src/main/java/io/javalin/http/servlet/JavalinServletContext.kt
Fixes #1752 
In most cases this bug only spams in console as it's trying to create new compressed stream when the stream is already closed. If it'll happen in async ctx, then we're not properly closing async ctx, because it won't be executed:
```
if (isAsync()) req().asyncContext.complete() // guarantee completion of async context to eliminate the possibility of hanging connections
```
Because it happens in `finally` closure & we don't do anything after that, I'm kinda unable to write unit test without modifying this code. Our execution flow is valid, it was pretty much just a typo
> [servlet] Replace invalid `isReady` call with `isInitialized()` (Fix #1752)

- javalin/src/main/java/io/javalin/plugin/bundled/SslRedirectPlugin.kt
- javalin/src/test/java/io/javalin/TestSslRedirectPlugin.kt
> [ssl-redirect-plugin] Support custom SSL port & cover SslRedirectPlugin with tests 

- javalin/src/main/java/io/javalin/security/AccessManager.kt
Since there is no `core` in the `JavalinConfig`, you have to access the `accessManager` setter directly through that config.
> Update log message in AccessManager.kt

- javalin/src/test/java/io/javalin/TestJavalinGson.kt
- javalin/src/test/java/io/javalin/TestJavalinJackson.kt
- javalin/src/test/java/io/javalin/TestJson.kt
- javalin/src/test/java/io/javalin/TestJsonMapper.kt
Move some functions out of `TestJson` and into respective test classes for `JavalinJackson`, `JavalinGson`, and `JsonMapper`.
Fix copy/paste/typo bug in `convertLargeStreamToJson` to use the `jsonMapper` arg rather than a hardwired `JavalinJackson` mapper.
> Reorganize JavalinJackson, JavalinGson, and JsonMapper test classes

- javalin/src/main/java/io/javalin/jetty/JettyResourceHandler.kt
Jetty 11.0.14 has this by default and the behaviour is covered with tests.
> Remove mimetype workaround for text/javascript

- pom.xml
https://nvd.nist.gov/vuln/detail/CVE-2023-26048
https://nvd.nist.gov/vuln/detail/CVE-2023-26049
This issue has been patched in versions 9.4.51, 10.0.14, and 11.0.14.
> Bump jetty version to satisfy owasp CVE-2023-26048, CVE-2023-26049

- .github/workflows/publish-snapshots.yml
Closes #1871
Since the only state where the version is not a snapshot happens when using the `mvn release:prepare` goal, we can just skip snapshots for this specific commit.
> Fix snapshot release workflow

- javalin/src/main/java/io/javalin/http/ContentType.kt
Add support to AVIF MIME type in ContentType enum
This is already supported by Jetty
> Support AVIF in ContentType

- javalin/src/main/java/io/javalin/websocket/WsContext.kt
Present in docs: 
But not in code:
> Add missing `headerAsClass` to `WsContext`

- javalin-bundle/pom.xml
- javalin/pom.xml
- javalin/src/main/java/io/javalin/compression/CompressionStrategy.kt
- javalin/src/main/java/io/javalin/compression/impl/Brotli4jCompressor.kt
- javalin/src/main/java/io/javalin/jetty/JettyPrecompressingResourceHandler.kt
- javalin/src/main/java/io/javalin/util/OptionalDependency.kt
- javalin/src/test/java/io/javalin/TestCompression.kt
- pom.xml
Closes #1890 
Previous discussion: #1891 
- It uses the latest version of Brotli ([v1.0.9](https://github.com/google/brotli/releases/tag/v1.0.9)) and fixes https://github.com/advisories/GHSA-5v8v-66v8-mwm7
- Adds support for `Aarch64` Linux and Macos and `ARMv7` Linux
- It's tested on JDK 11, JDK 17
- It is actively developed
- Uses JPMS
- Another optional dependency
> [compression] Add `brotli4j` support and make it default in `javalin-bundle`

- javalin/src/main/java/io/javalin/config/JettyConfig.kt
- javalin/src/main/java/io/javalin/config/PrivateConfig.kt
- javalin/src/main/java/io/javalin/jetty/JettyServer.kt
- javalin/src/test/java/io/javalin/TestCustomJettyHttpConfiguration.kt
- javalin/src/test/java/io/javalin/TestJettyCustomizers.kt
closes javalin/javalin#1909
@tipsy 
as requested I've refactored this to use a Consumer<HttpConfiguration>.  I've then changed the warning message in the JettyServer to reflect this and changed the test to make sure it still works
> Ability to set Jetty HttpConfiguration easily

- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/main/java/io/javalin/validation/BaseValidator.kt
- javalin/src/main/java/io/javalin/validation/NullableValidator.kt
- javalin/src/main/java/io/javalin/validation/Validator.kt
- javalin/src/test/java/io/javalin/TestValidation.kt
- javalin/src/test/java/io/javalin/TestValidation_Java.java
This uses a completely unsafe `queryParams(key).joinToString("|")` and `if (stringSource.stringValue?.contains("|") == true)`. This is easy enough to rewrite, it's just a quick way to get a PR up for discussion.
Context: 
```kotlin
/** Creates a typed [Validator] for the queryParams() value */
fun <T> queryParamsAsClass(key: String, clazz: Class<T>): Validator<List<T>> =
Validator.create(clazz, queryParams(key).joinToString("|"), key) as Validator<List<T>>
```
Usage:
```kotlin
@Test
fun `queryParams can be used to validate list`() = TestUtil.test { app, http ->
app.get("/") {
it.queryParamsAsClass<Int>("param")
.check({ it.all { it < 5 } }, "All must be smaller than 5")
.get()
}
val response = http.get("/?param=1&param=2&param=5")
assertThat(response.status).isEqualTo(BAD_REQUEST.code) …
```
> [validation] Add queryParamsAsClass method

- javalin/src/main/java/io/javalin/http/servlet/JavalinServlet.kt
- javalin/src/main/java/io/javalin/http/servlet/JavalinServletContext.kt
- javalin/src/main/java/io/javalin/jetty/JavalinJettyServlet.kt
This PR:
* Replaces global `JavalinConfig` with dedicated `JavalinServletContextConfig`
* Replaces 2 references to objects with 1 reference to constant cfg instance
* Creates a space for further properties pulled out from global cfg
> [context] Remove dependency on `JavalinConfig` & reduce Context size by 8 bytes

- javalin/module-info.java
- pom.xml
1. org.jetbrains.annotations is now a static (optional) dependency in **module-info.java**.
2. org.jetbrains.annotations is now marked as `<scope>provided</scope>` in **pom.xml**.
I'm not 100% sure about point 2, since I'm not a Maven user.
I searched for "maven compile time only dependency" and according to this old Stackoverflow answer [Is there a Maven "compiler-only" scope for dependency artifacts](https://stackoverflow.com/questions/12824112/is-there-a-maven-compiler-only-scope-for-dependency-artifacts) and [Maven Dependency Scopes](https://www.baeldung.com/maven-dependency-scopes) this is the way to exclude the jar from being a runtime dependency.
Fixes #1947
> Make Jetbrains annotations an optional dependency

- javalin/src/main/java/io/javalin/Javalin.java
- javalin/src/test/java/io/javalin/TestAccessManager.kt
- javalin/src/test/java/io/javalin/TestMultipartForms.kt
- javalin/src/test/java/io/javalin/TestPlugins.kt
- javalin/src/test/java/io/javalin/staticfiles/TestStaticFiles.kt
This is a part of #1894. We should remove this method, not only because it's against our further goals, but what's more important, because it's an entry point in the official API for users to access properties that results in undefined behaviors.
> [config] Remove `Javalin.updateConfig`

- javalin/src/main/java/io/javalin/compression/CompressedStream.kt
- javalin/src/main/java/io/javalin/compression/CompressionStrategy.kt
- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/main/java/io/javalin/http/servlet/JavalinServletContext.kt
- javalin/src/test/java/io/javalin/TestCompression.kt
A request scope attribute `ALWAYS_COMPRESS` will signal that a compression stream should always be created, if allowed. This attribute is now used for the `writeJsonStream()` call, where the total bytes to write cannot be known in advance.
The evaluation of creating a compressed stream or not was reworked to only evaluate only once.
closes #1950
> Change when a compression stream is created

- javalin/src/main/java/io/javalin/jetty/JettyPrecompressingResourceHandler.kt
- javalin/src/test/java/io/javalin/staticfiles/TestStaticFilesPrecompressor.kt
`acceptEncoding` and `contentEncoding` headers were improperly handled. Closes #1958
> Fix `JettyPrecompressingResourceHandler` regression in #904e360 (5x)

- javalin/src/main/java/io/javalin/jetty/JettyPrecompressingResourceHandler.kt
- javalin/src/main/java/io/javalin/jetty/JettyResourceHandler.kt
- javalin/src/test/java/io/javalin/TestWebBrowser.kt
- javalin/src/test/java/io/javalin/staticfiles/TestStaticFilesPrecompressor.kt
`acceptEncoding` and `contentEncoding` headers were improperly handled.
Closes #1958
> Fix `JettyPrecompressingResourceHandler` regression in #904e360 (6x)

- javalin/src/main/java/io/javalin/http/ContentType.kt
This PR adds WOFF/WOFF2 mentioned by [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types)
Resolves #1934
> [content-type] Support FONT_WOFF & FONT_WOFF2

- javalin/src/main/java/io/javalin/http/servlet/ErrorMapper.kt
- javalin/src/main/java/io/javalin/http/servlet/JavalinServletContext.kt
- javalin/src/main/java/io/javalin/jetty/JettyResourceHandler.kt
- javalin/src/main/java/io/javalin/json/JavalinJackson.kt
- javalin/src/main/java/io/javalin/json/PipedStreamUtil.kt
- javalin/src/main/java/io/javalin/routing/ParserState.kt
- javalin/src/main/java/io/javalin/util/ConcurrencyUtil.kt
- javalin/src/main/java/io/javalin/validation/BaseValidator.kt
- javalin/src/main/java/io/javalin/vue/VueFileInliner.kt
- javalin/src/main/java/io/javalin/vue/VueHandler.kt
- javalin/src/main/java/io/javalin/vue/VuePathMaster.kt
- javalin/src/main/java/io/javalin/websocket/WsAutomaticPing.kt
- javalin/src/main/java/io/javalin/websocket/WsConnection.kt
- javalin/src/main/java/io/javalin/websocket/WsContext.kt
- javalin/src/test/java/io/javalin/TestConcurrencyUtil.kt
It'll most likely resolve #1966
> [loom] Avoid synchronized lazy values in blocking context and replace required sync lazy inits with ReentrantLock when Loom is enabled

- javalin/src/main/java/io/javalin/jetty/JettyServer.kt
- javalin/src/test/java/io/javalin/TestCustomJetty.kt
I recently migrated an application from spark to javalin 5, and we use
the sentry servlet integration to enrich our sentry error reporting, and
noticed it wasn't actually getting called in the javalin app.
The default ContextHandler's `doHandle` method does the necessary
invocations of `ServletRequestListener`s that have been registered, and
I think just calling `super` to get that handling in `wsAndHttpHandler` is
the correct behavior, but maybe there was some reason that it intentionally
did not call `super.doHandle` that I missed.  It appears this will be a
non-issue in Javalin 6 since this handling was refactored in a way that
removed the method override, but I think this is worth fixing in Javalin 5.
> Fix request listeners registered in contextHandlerConfig

- javalin/module-info.java
We're not getting IDE warnings because of the move from #1923.
> [meta] Fix wrong package name in `module-info.java`

- javalin/src/main/java/io/javalin/jetty/JettyResourceHandler.kt
- javalin/src/test/java/io/javalin/staticfiles/TestStaticFiles.kt
- Fixes #1944 - Handling the case when URL path exactly matches the hostedPath of a resource (Reproducible when URL without trailing slash is used to reach a resource with custom hostedPath)
- Added a unit test for this specific case
- Without the fix, the new test would fail with:
`io.javalin.staticfiles.TestStaticFiles.directory root returns welcome file, when custom hostedPath matches path  Time elapsed: 0.024 s  <<< ERROR!
java.lang.RuntimeException: 
java.lang.Exception: Assertion error: 
expected: 200 OK
but was: 404 Not Found
at io.javalin.testing.TestUtil.test(TestUtil.java:38)`
> [javalin] Handling path == hostedPath edge-case in JettyResourceHandles - #1944

- javalin/src/main/java/io/javalin/jetty/JettyResourceHandler.kt
- javalin/src/test/java/io/javalin/staticfiles/TestStaticFiles.kt
Clone of https://github.com/javalin/javalin/pull/2003 for master.
- Fixes #1944 - Handling the case when URL path exactly matches the hostedPath of a resource (Reproducible when URL without trailing slash is used to reach a resource with custom hostedPath)
- Added a unit test for this specific case
- Without the fix, the new test would fail with:
`io.javalin.staticfiles.TestStaticFiles.directory root returns welcome file, when custom hostedPath matches path  Time elapsed: 0.024 s  <<< ERROR!
java.lang.RuntimeException: 
java.lang.Exception: Assertion error: 
expected: 200 OK
but was: 404 Not Found
at io.javalin.testing.TestUtil.test(TestUtil.java:38)`
> fix: fixing erroneous 404 for welcome-file edge-case [master]

- javalin/src/main/java/io/javalin/event/EventManager.kt
- javalin/src/main/java/io/javalin/http/HttpStatus.kt
- javalin/src/main/java/io/javalin/router/matcher/PathMatcher.kt
- javalin/src/main/java/io/javalin/websocket/WsPathMatcher.kt
- javalin/src/test/java/io/javalin/http/ContentTypeTest.kt
- javalin/src/test/java/io/javalin/http/HttpResponseExceptionTest.kt
- javalin/src/test/java/io/javalin/http/HttpStatusCodeTest.kt
- javalin/src/test/java/io/javalin/performance/PathMatcherBenchmark.java
https://kotlinlang.org/docs/whatsnew19.html#stable-replacement-of-the-enum-class-values-function
> [cleanup] Use cached `Enum.entries` from Kotlin 1.9 instead of `Enum.values()`

- pom.xml
Updated the Jetty dependency to version `11.0.17`.
Fixes #2017.
> Update Jetty Dependency to Version 11.0.17

- javalin/src/main/java/io/javalin/Javalin.java
- javalin/src/main/java/io/javalin/config/JavalinConfig.kt
- javalin/src/main/java/io/javalin/jetty/JettyServer.kt
Currently, Javalin notifies users that the app instance hasn't been started. Indeed, it is user-friendly behavior for `app.create().start()`, but has some drawbacks:
1. It spawns a new thread just for that one functionality - it's problematic for apps that try to run on low resources, the startup procedure of JVM, libraries & the app itself highly pressures GC & heap at this particular time
2. On slow machines, like e.g. concurrent tests on CI on ARM targets may not be able to actually start a server in 5s (especially when config scope grows and e.g. tries to establish a connection to db)
3. It's not useful anymore for `createAndStart`
> [config] Add a possibility to disable startup watcher

- javalin/src/main/java/io/javalin/config/BundledPluginsConfig.kt
- javalin/src/main/java/io/javalin/config/ContextResolverConfig.kt
- javalin/src/main/java/io/javalin/config/EventConfig.kt
- javalin/src/main/java/io/javalin/config/HttpConfig.kt
- javalin/src/main/java/io/javalin/config/JavalinConfig.kt
- javalin/src/main/java/io/javalin/config/JettyConfig.kt
- javalin/src/main/java/io/javalin/config/RequestLoggerConfig.kt
- javalin/src/main/java/io/javalin/config/RouterConfig.kt
- javalin/src/main/java/io/javalin/config/SpaRootConfig.kt
- javalin/src/main/java/io/javalin/config/StaticFilesConfig.kt
- javalin/src/main/java/io/javalin/event/EventManager.kt
- javalin/src/main/java/io/javalin/http/Cookie.kt
- javalin/src/main/java/io/javalin/http/ExceptionHandler.java
- javalin/src/main/java/io/javalin/http/Handler.java
- javalin/src/main/java/io/javalin/http/HandlerType.kt
- javalin/src/main/java/io/javalin/http/HttpStatus.kt
- javalin/src/main/java/io/javalin/http/RequestLogger.java
- javalin/src/main/java/io/javalin/http/staticfiles/StaticFileConfig.kt
- javalin/src/main/java/io/javalin/plugin/bundled/CorsPlugin.kt
- javalin/src/main/java/io/javalin/plugin/bundled/DevLoggerPlugin.kt
- javalin/src/main/java/io/javalin/plugin/bundled/GlobalHeadersPlugin.kt
- javalin/src/main/java/io/javalin/plugin/bundled/HttpAllowedMethodsPlugin.kt
- javalin/src/main/java/io/javalin/plugin/bundled/RouteOverviewPlugin.kt
- javalin/src/main/java/io/javalin/rendering/FileRenderer.kt
- javalin/src/main/java/io/javalin/vue/JavalinVueConfig.kt
This PR adds Javadoc/KDoc documentation on public classes, data classes, functions and enums to make it easier to use from IDEs. 
Fixes #2016 
Specifically:  
> [!NOTE]
> Most documentation text was copy-pasted from the [MDN Docs](https://developer.mozilla.org/en-US/docs) pages, and the Javalin documentation pages.
> Add missing javadoc 

- javalin-testtools/src/test/java/io/javalin/testtools/JavaTest.java
- javalin-testtools/src/test/kotlin/io/javalin/testtools/KotlinTest.kt
- javalin/src/main/java/io/javalin/http/servlet/DefaultTasks.kt
- javalin/src/main/java/io/javalin/router/Endpoint.kt
- javalin/src/main/java/io/javalin/router/exception/ExceptionMapper.kt
- javalin/src/main/java/io/javalin/router/matcher/ParserExceptions.kt
- javalin/src/test/java/io/javalin/TestBeforeAfterMatched.kt
- javalin/src/test/java/io/javalin/TestFilters.kt
- javalin/src/test/java/io/javalin/TestRouting.kt
- javalin/src/test/java/io/javalin/TestTrailingSlashes.kt
- javalin/src/test/java/io/javalin/staticfiles/TestSinglePageMode.kt
- javalin/src/test/java/io/javalin/staticfiles/TestStaticDirectorySlash.kt
- javalin/src/test/java/io/javalin/staticfiles/TestStaticFiles.kt
Pros:
1. Provides an easy way to distinguish a non-existing endpoint from a non-existing resource/or other Handler-related response
2. Returns useful error message `Endpoint {http method} {uri} not found` instead of a generic `Not found` value
3. I've simplified & improved `ExceptionMapper` implementation, because it wasn't handling parent classes properly 
Cons:
1. A small change in the previous behavior (error message)
Requested on Discord.
> [servlet] Handle endpoint not found exception via `EndpointNotFound`

- .editorconfig
- javalin-utils/javalin-context-mock/src/main/java/io/javalin/mock/ContextMock.kt
- javalin/src/main/java/io/javalin/config/JavalinConfig.kt
- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/main/java/io/javalin/http/servlet/JavalinServletContext.kt
- javalin/src/main/java/io/javalin/plugin/PluginApi.kt
- javalin/src/main/java/io/javalin/plugin/PluginExceptions.kt
- javalin/src/main/java/io/javalin/plugin/PluginManager.kt
- javalin/src/test/java/io/javalin/TestPlugins.kt
- javalin/src/test/java/io/javalin/TestPublicApi_Java.java
This is another attempt at the concept of #2054
This PR introduces the `ContextExtendingPlugin` interface, which extends the normal `Plugin` interface and adds a required `withContextExtension` method which consumes a `Context` object and returns a "context extension", which can be an object of any type but is intended to be a context-related object to use fluently like `ctx.with(MyCustomRenderingPlugin).fancyRender(model)`
`with` was chosen as the method name because it makes the expression read fluidly.  Plugins are almost always named like `WhateverPlugin`, so it's easy to tell when reading usages that it is plugin related, and it reads more fluently and less repetitively than `ctx.plugin(MyCustomRenderingPlugin).fancyRender(model)`.  The way this is coupled to plugins and uses the …
> Introduce context extending plugins

- javalin/src/main/java/io/javalin/http/staticfiles/StaticFileConfig.kt
This gets invoked and presented on the console during startup, and shows which mimetypes are registered for a file extension. Previously, the message included something like 
```
2024-01-09 21:20:03,840 INFO  i.j.Javalin Static file handler added: StaticFileConfig(
hostedPath=/, directory=src/main/resources/public, location=EXTERNAL, precompress=false, 
aliasCheck=null, headers={Cache-Control=max-age=0}, 
mimeTypes=io.javalin.http.staticfiles.MimeTypesConfig@46d567cb). 
File system location: 'src/main/resources/public'
```
Note the **mimeTypes=io.javalin.http.staticfiles.MimeTypesConfig@46d567cb**.
It now is formatted as `mimeTypes={csv=text/csv}`, or just `{}` if it's empty.
> Give StaticFileConfig a proper toString

- javalin/src/main/java/io/javalin/jetty/JettyResourceHandler.kt
- javalin/src/test/java/io/javalin/staticfiles/TestStaticFilesEdgeCases.kt
When the requested, external, static resource path doesn't exist print the normalized absolute path, rather than the value provided by the user. The path may be missing due to an incorrect working directory or other issue that exists at a level higher than the relative path the user gave.
> Static resources: Print the absolute path when there's a problem

- javalin/src/main/java/io/javalin/config/RouterConfig.kt
It allows to overload this method with extension function in other module. We already use this for the other mount function.
> [routing] Mark RouterConfig.mount(JavalinDefaultRouting) as low priority function

- .github/workflows/publish-snapshots.yml
Reverts part of the https://github.com/javalin/javalin/commit/64ccbe17724261cb38fa59dabb0d4131f7e1449d
Related to https://github.com/javalin/javalin/issues/2117
> [distribution] Revert 64ccbe1 and use JDK11 for snapshots GH-2117

- javalin/src/main/java/io/javalin/plugin/bundled/CorsUtils.kt
- javalin/src/test/java/io/javalin/TestCors.kt
This fixes the Exception as described in #2104.
Will do another PR soon to rewrite it using the JDK's URI class.
Fixes #2104
> Check for dot in client side host when using wildcard hosts

- javalin/src/test/java/io/javalin/TestMultipartForms.kt
This case covers LF on Windows and CRLF on Unix systems
> Check for actual line ending before asserting content

- javalin/src/main/java/io/javalin/plugin/bundled/CorsUtils.kt
- pom.xml
Backport of #2133 for Javalin 5 as discussed on Discord.
> [cors] Check for dot in client side host when using wildcard hosts (5.x)

- javalin/module-info.java
fixes https://github.com/javalin/javalin/issues/2136
> Add uses for SLF4J

- javalin/src/main/java/io/javalin/http/servlet/JavalinServletContext.kt
- javalin/src/test/java/io/javalin/TestBodyReading.kt
Bodies may exist but not contain valid form params for some requests,
and we should handle trying to read params from those requests gracefully
> Handle invalid urlencoding in bodies

- javalin/src/main/java/io/javalin/http/util/ContextUtil.kt
- javalin/src/test/java/io/javalin/TestBodyReading.kt
Bodies may exist but not contain valid form params for some requests, and we should handle trying to read params from those requests gracefully.
"backport" of https://github.com/javalin/javalin/pull/2245 for javalin 4x.
> [javalin-4x][context] Handle invalid urlencoding in bodies

- javalin-utils/javalin-context-mock/src/main/java/io/javalin/mock/ContextMock.kt
- javalin/src/main/java/io/javalin/config/HttpConfig.kt
- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/main/java/io/javalin/http/servlet/JavalinServletContext.kt
- javalin/src/test/java/io/javalin/TestBodyReading.kt
- javalin/src/test/java/io/javalin/TestConfiguration.kt
- javalin/src/test/java/io/javalin/TestJavalinInstanceAndConfigApi.kt
- javalin/src/test/java/io/javalin/TestJavalinInstanceAndConfigApi_Java.java
- javalin/src/test/java/io/javalin/TestJson.kt
This is valuable for being able to unconditionally use formParams
in an application without risking consuming the body stream on
requests where the client did not send form params.
For bodyAsClass/bodyStreamAsClass, this will throw a BadRequestResponse when trying to convert a non-JSON body to a class.  For formParams and friends, the formParam list will be empty when trying to read form params from a request with a non-form-param content type.
> Add config to enforce content types strictly

- javalin-osgi/README.md
- javalin-osgi/pom.xml
- pom.xml
This PR is similar to https://github.com/javalin/javalin/pull/1564 but aiming at Javalin v6.
> Enable OSGi bundle packaging for Javalin v6.

- .github/dependabot.yml
Now dependabot should create a single PR for the dependency updates. Example dependabot PR: https://github.com/SentryMan/avaje-javalin-api-example/pull/50
> Update Dependabot to actually group dependency updates

- javalin/src/main/java/io/javalin/plugin/bundled/CorsPlugin.kt
- javalin/src/test/java/io/javalin/TestCors.kt
While helping people with CORS this is one thing I have seen people use and then getting confused as to why it doesn't work. This is already documented in the cors plugin page but catching this on startup should be a better experience.
This is technically a breaking change but as browsers already reject this combination should be considered a bug fix as we adopt the browser behaviour, leading to a better experience as you now get immediate feedback on what went wrong instead of having to debug this in a browser.
> [cors] Disallow anyHost + allowCredentials

- javalin/src/main/java/io/javalin/http/Cookie.kt
The existing docs are incorrect regarding negative numbers for `Cookie` `maxAge`. This PR copies the docs from [here](https://jakarta.ee/specifications/servlet/4.0/apidocs/javax/servlet/http/cookie#setMaxAge-int-) to fix it.
> [core] Fix `Cookie` `maxAge` docs

- javalin/src/main/java/io/javalin/config/HttpConfig.kt
- javalin/src/main/java/io/javalin/http/servlet/JavalinServlet.kt
- javalin/src/main/java/io/javalin/jetty/JettyServer.kt
- javalin/src/test/java/io/javalin/TestCustomJettyHttpConfiguration.kt
As discussed on Discord:
This PR adds a config option for the response buffer size that used to be the [Kotlin default of 8kb](https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/jvm/src/kotlin/io/Constants.kt#L13) and was set explicitly to 4096.
The new default is the same what Jetty has by default.
Link to the small discussion on Discord: https://discord.com/channels/804862058528505896/805106384977920040/1336426384981102663
> [http] Add config option for response buffer size with a new default

- javalin/src/main/java/io/javalin/http/HttpStatus.kt
The current `HttpStatus.forStatus` implementation appears to be a brute force search:
https://github.com/javalin/javalin/blob/2b63b76fd4b262c4eb8ff5187926e83bd2dd6129/javalin/src/main/java/io/javalin/http/HttpStatus.kt#L153-L154
This PR changes the `HttpStatus.forStatus` implementation to use a map lookup, similar to [`HandlerType.findByName`](https://github.com/javalin/javalin/blob/2b63b76fd4b262c4eb8ff5187926e83bd2dd6129/javalin/src/main/java/io/javalin/http/HandlerType.kt#L106-L112).
> [core] Improve `HttpStatus.forStatus` by using map lookup

- javalin-micrometer/src/main/java/io/javalin/micrometer/MicrometerPlugin.kt
- javalin-micrometer/src/test/kotlin/io/javalin/micrometer/MicrometerPluginTest.kt
When requests come in with invalid methods (e.g. POSTS instead of POST) the exisitng  plugin fails to find the method and throws an exception (meaning no metrics are emitted).
Change to use the existng `findByName` method so that metrics are emitted. 
Created an issue https://github.com/javalin/javalin/issues/2366 to track this.
> Handle invalid http verbs in micrometer plugin

- javalin/src/main/java/io/javalin/config/JettyConfig.kt
- javalin/src/main/java/io/javalin/config/PrivateConfig.kt
- javalin/src/main/java/io/javalin/config/RouterConfig.kt
- javalin/src/main/java/io/javalin/http/HttpResponseException.kt
- javalin/src/main/java/io/javalin/http/HttpStatus.kt
- javalin/src/main/java/io/javalin/router/InternalRouter.kt
- javalin/src/main/java/io/javalin/router/exception/ExceptionMapper.kt
- javalin/src/test/java/io/javalin/TestExceptionMapper.kt
Map client aborts to 499 and timeouts to 408.
Previously, both were returned as 500, mixing them with genuine server errors. Now, client disconnects are tracked as 499 (Client Closed Request), and request timeouts produce 408 (Request Timeout) to better categorize errors in logs and monitoring tools.
- **Author:** @martinsk82 [martin.kozlowski@mercadolibre.com]
- **Affiliation:** MercadoLibre
- **OSPO Contact:** ospo@mercadolibre.com
- **Context:** Strategic collaboration from Mercadolibre's internal Open Source Program Office (OSPO)
> Map client aborts to 499 and timeouts to 408.

- javalin-micrometer/pom.xml
When updating micrometer to the latest version (1.14.5) the tests fail. 
This should be investigated more, but until then we could update the 1.13 dependency to the latest patch version.
> Update micrometer to latest patch version

- pom.xml
This output is showing while running tests:
> Mockito is currently self-attaching to enable the inline-mock-maker. This will no longer work
in future releases of the JDK. Please add Mockito as an agent to your build what is describe
d in Mockito's documentation: https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mock
ito/Mockito.html#0.3
Not sure where that documentation is, link doesn't seem right, but following [this Stack Overflow answer](https://stackoverflow.com/a/79213258/1132101) this should be the way, and it does work.
> [tests] Add java argument to surefire for mockito as a java agent

- javalin-rendering/pom.xml
- pom.xml
Updates some more dependencies. I believe all dependencies are now updated to their latest released version, except the following:
* Kotlin 2 and JTE 3 (see [here](https://github.com/javalin/javalin/pull/2392))
* Jetty 12 (see [here](https://github.com/javalin/javalin/issues/2067)) 
* Dokka plugin (mentioned [here](https://github.com/javalin/javalin/blob/f7d5fa7068d23c2532cf5a9551b7537e83f5522b/pom.xml#L74), did not investigate further)
* Pebble 3.2 (tests break, did not investigate much, is it perhaps related to [this](https://github.com/javalin/javalin/blob/f7d5fa7068d23c2532cf5a9551b7537e83f5522b/javalin-rendering/src/main/java/io/javalin/rendering/util/RenderingDependency.kt#L26)?)
> [deps] Some further minor and patch version updates

- javalin/src/main/java/io/javalin/util/ConcurrencyUtil.kt
Relevant issue: #2192 
Fix proposed on issue.
Created a new class (VirtualThreadBuilder) for fixing virtual threads enabled bug on native images for graalVM.
> Fix virtual threads enabled bug on native images for graalVM

- .github/workflows/main.yml
- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/test/java/io/javalin/TestCompression.kt
This PR adds `Context.disableCompression()` to allow disabling response compression on a per-endpoint basis.
Implements the feature discussed in [#2372](https://github.com/javalin/javalin/issues/2372).
Let me know if there’s anything I should refine before this can be merged.
> feat: add Context.disableCompression() to disable response compression

- javalin/src/main/java/io/javalin/jetty/JettyResourceHandler.kt
- javalin/src/test/java/io/javalin/staticfiles/TestStaticFiles.kt
Create static files with special characters and access using the encoded path.
Workflow result:
https://github.com/hupender/javalin/actions/runs/15058856533
> [Static Files] access files with special characters using encoded path

- javalin/src/main/java/io/javalin/config/StaticFilesConfig.kt
- javalin/src/main/java/io/javalin/http/servlet/DefaultTasks.kt
- javalin/src/main/java/io/javalin/http/staticfiles/ResourceHandler.java
- javalin/src/main/java/io/javalin/http/staticfiles/StaticFileConfig.kt
- javalin/src/main/java/io/javalin/jetty/JettyResourceHandler.kt
- javalin/src/test/java/io/javalin/staticfiles/TestStaticFileAccess.kt
Provided feature for the issue  https://github.com/javalin/javalin/issues/2364.
Example use case : 
``` Java 
var app = Javalin
.create(config -> {
config.staticFiles.add(staticFileConfig -> {
staticFileConfig.hostedPath = "/";
staticFileConfig.directory = "/public";
staticFileConfig.location = Location.CLASSPATH;
staticFileConfig.roles = Set.of(Role.USER);
});
})
.start();
```
> feat: Add route roles for static files

- javalin/src/main/java/io/javalin/http/servlet/JavalinServletContext.kt
- javalin/src/test/java/io/javalin/http/ContentTypeTest.kt
Small fix regarding quoted charset parameter in content-type header. 
Content-type headers like `application/json;charset="utf-8"` were causing errors.
Changed content-type header parsing to handle both quoted and unquoted values and added a parameterized test for verification.
Fixes #2448
> [context] add support for quoted charset in content-type header (#2448)

- javalin/src/main/java/io/javalin/compression/CompressedStream.kt
- javalin/src/main/java/io/javalin/compression/CompressionStrategy.kt
- javalin/src/main/java/io/javalin/jetty/JettyPrecompressingResourceHandler.kt
- javalin/src/test/java/io/javalin/TestCompression.kt
I was missing a way to select a preferred compression type server side. Currently the first compression type supported by both the client and the server is selected, usually browsers send brotli as last, which resulted in gzip to always be favored over it.
I added a new List that allows us to specify our preference on the server side by priority (according to the order of the elements in the list).
I never programmed in Kotlin and it's my first contribution to this project, so please guide me how to get the pull request ready to merge.
> [compression] Add preferred compressors list
