- src/main/java/io/javalin/Javalin.java
- src/main/java/io/javalin/core/JavalinServlet.kt
- src/main/java/io/javalin/core/PathMatcher.kt
- src/test/java/io/javalin/TestIgnoreTrailingSlashes.java
> Enchantinggg4

- src/test/java/io/javalin/TestFileUpload.java
> Test file upload

- src/main/java/io/javalin/Context.kt
Removes explicit multipart type from isMultiPart() implementation
("multipart/form-data" -> "multipart/")
> [#96] Changes the isMultiPart() implementation

- CONTRIBUTING.md
- src/main/java/io/javalin/embeddedserver/jetty/websocket/WebSocketHandler.java
- src/main/java/io/javalin/embeddedserver/jetty/websocket/WsSession.kt
- src/test/java/io/javalin/TestWebSocket.java
Initial work. Not ready for merge. How does this look so far @tipsy ?
> Implement basic session identification and tracking

- src/main/java/io/javalin/Javalin.java
- src/main/java/io/javalin/core/JavalinServlet.kt
- src/test/java/io/javalin/TestDefaultContentType.java
> [core] Allow setting default content type and character encoding

- src/main/java/io/javalin/Context.kt
- src/main/java/io/javalin/builder/CookieBuilder.kt
Updated cookie builder class to look more Kotlin and more builder (added `build()` method). 
Moved cookie store to a separate class to encapsulate its functionality.
Added lazy initialization for `cookieStore` in `Context`.
> Cookie builder update

- src/main/java/io/javalin/ApiBuilder.java
- src/main/java/io/javalin/core/PathMatcher.kt
- src/main/java/io/javalin/core/util/ContextUtil.kt
- src/test/java/io/javalin/TestRouting.java
- src/test/java/io/javalin/performance/RouteMatcherPerformanceTest.kt
- src/test/java/io/javalin/performance/StupidPerformanceTest.java
Just an example for the feedback
> Use regular expressions for matching paths

- src/main/java/io/javalin/Context.kt
- src/main/java/io/javalin/core/ExceptionMapper.kt
- src/main/java/io/javalin/core/JavalinServlet.kt
- Fixes gzip on streams.
- Simplifies Javalin servlet class.
- Applies correct charset to result string.
> Use stream for response string output

- src/main/java/io/javalin/core/util/RouteOverviewUtil.kt
- src/test/java/io/javalin/routeoverview/RouteOverviewUtilWrapper.java
- src/test/java/io/javalin/routeoverview/TestRouteOverview_Java.java
- src/test/java/io/javalin/routeoverview/TestRouteOverview_Kotlin.kt
- src/test/java/io/javalin/routeoverview/TestRouteOverview_visual.java
Not really a final version. Kinda works though.
As a bonus, kotlin is able to retrieve enclosing method name for lambdas, so it could be like `Impl.runFrom::??? (anonymous lambda)`
> Add some reflection in route overview

- src/main/java/io/javalin/ApiBuilder.java
- src/main/java/io/javalin/Context.kt
- src/main/java/io/javalin/Javalin.java
- src/main/java/io/javalin/embeddedserver/EmbeddedServer.kt
- src/main/java/io/javalin/embeddedserver/EmbeddedServerFactory.kt
- src/main/java/io/javalin/embeddedserver/StaticResourceHandler.kt
- src/main/java/io/javalin/embeddedserver/jetty/EmbeddedJettyFactory.kt
- src/main/java/io/javalin/security/AccessManager.java
- src/main/java/io/javalin/security/Role.java
> Add Javadoc for public API

- pom.xml
- src/main/java/io/javalin/core/PathMatcher.kt
- src/test/java/io/javalin/TestRouting.java
>  Expect at least one non-slash for the param in path matcher

- src/main/java/io/javalin/embeddedserver/jetty/websocket/WsSession.kt
- src/test/java/io/javalin/TestWebSocket.java
Added `header(String) String`, `headerMap() Map<String, String>` and `host(String) String` to `WsSession`
> WSSession host() and header()

- src/main/java/io/javalin/Context.kt
- src/main/java/io/javalin/ExceptionHandler.java
- src/main/java/io/javalin/core/ExceptionMapper.kt
- src/main/java/io/javalin/core/JavalinServlet.kt
- src/main/java/io/javalin/core/util/ContextUtil.kt
- src/main/java/io/javalin/core/util/LogUtil.kt
- src/main/java/io/javalin/embeddedserver/jetty/EmbeddedJettyServer.kt
- src/main/java/io/javalin/embeddedserver/jetty/websocket/WebSocketConfig.java
- src/main/java/io/javalin/embeddedserver/jetty/websocket/WebSocketHandler.java
- src/test/java/io/javalin/TestAsync.java
- src/test/java/io/javalin/TestFuture.java
> Add Context.result(CompletableFuture)

- src/main/java/io/javalin/translator/json/Jackson.kt
This is an implementation for #200, let me know if you think anything is missing. I haven't tested it, primarily because I'm not sure how to. If you could give me a pointer as to how to implement a test for this I'll give it a shot.
> Initialize Jackson ObjectMapper with KotlinModule

- src/main/java/io/javalin/Javalin.java
resolves #220 
Adds new method `dontShowBannerInLogs()` to javalin insatnce, by which user can disable javalin banner if required.
> [core] Add option to disable javalin banner

- src/main/java/io/javalin/Context.kt
- src/main/java/io/javalin/core/util/ContextUtil.kt
- src/main/java/io/javalin/core/util/LogUtil.kt
- src/main/java/io/javalin/core/util/MultipartUtil.kt
- src/main/java/io/javalin/core/websocket/WsSession.kt
- src/test/java/io/javalin/TestBodyReading.java
- src/test/java/io/javalin/TestMultipartForms.java
- src/test/java/io/javalin/TestRequest.java
Changing return values of Array<T> in ctx API to List<T> #239
> Changing all return values of Array<T> in API to List<T>

- src/main/java/io/javalin/Context.kt
- src/main/java/io/javalin/core/websocket/WsSession.kt
- src/test/java/io/javalin/TestRequest.java
Changing form/queryParams(x) to return empty lists instead of null values #239
> form/queryParams -> empty lists

- src/main/java/io/javalin/core/util/ContextUtil.kt
fix issue #260
return empty Map when parameter string is empty
> ContextUtil.splitKeyValueStringAndGroupByKey fix

- pom.xml
- src/main/java/io/javalin/rendering/template/JavalinVelocity.kt
> upgrade velocity to version 2.0

- src/main/java/io/javalin/websocket/BinaryMessageHandler.java
- src/main/java/io/javalin/websocket/WsHandler.java
- src/main/java/io/javalin/websocket/WsPathMatcher.kt
- src/main/java/io/javalin/websocket/WsSession.kt
- src/test/java/io/javalin/TestWebSocket.kt
> #318 Add handling for binary messages

- src/main/java/io/javalin/EventListener.java
https://github.com/tipsy/javalin/issues/333#issuecomment-414767860
Here’s a first attempt. I followed what I found in `Handler.java`, but I don’t know if it works.
> Allow event handlers to throw checked exceptions

- src/main/java/io/javalin/Context.kt
> Set Content-Type before resolving charset and writing body

- src/main/java/io/javalin/Context.kt
- src/test/java/io/javalin/validation/TestValidation.kt
> Adding default param to content validate methods

- .travis.yml
- pom.xml
generate Automatic-Module-Name and update for build java9+. 
#206 
example of MANIFEST.MF with automatic-module:
> Automatic-Module-Name #206

- src/main/java/io/javalin/validation/Validator.kt
- src/test/java/io/javalin/validation/TestValidation.kt
> Move null-check out of Validator constructor

- src/main/java/io/javalin/json/JavalinJackson.kt
> Expose JavalinJackson ObjectMapper

- src/main/java/io/javalin/core/util/JettyServerUtil.kt
- src/test/java/io/javalin/TestCustomJetty.kt
> Make it possible to use a custom HandlerCollection

- src/main/java/io/javalin/core/util/JettyServerUtil.kt
- src/test/java/io/javalin/TestCustomJetty.kt
I haven't written that much Kotlin, so you may want to refactor it.
> Fixes #399

- src/main/java/io/javalin/Javalin.java
- src/main/java/io/javalin/core/util/LogUtil.kt
- src/main/java/io/javalin/websocket/WsPathMatcher.kt
- src/test/java/io/javalin/TestWebSocket.kt
Supersedes #410 and this pull request only contains non-merged changes.
> Add wsLogger to Javalin (fixes #407)

- src/test/java/io/javalin/TestCustomJetty.kt
This tests the functionality in https://github.com/tipsy/javalin/pull/412
> [tests] Add test for handling of invalid session handler

- src/main/java/io/javalin/Extension.java
- src/main/java/io/javalin/Javalin.java
- src/test/java/io/javalin/TestExtension.java
> [core] add `register(Extension)` DSL

- pom.xml
Pull request made for compatibility to Kotlin 1.3 Projects. Also Jackson Databind and Kotlin Module now have the same version. Jetty upgrade.
> Kotlin upgrade. Jetty upgrade. Jackson consistency upgrade

- src/main/java/io/javalin/Javalin.java
This makes ease to create code generator or add routes dynamically
> Make Javalin.addHandler public

- src/main/java/io/javalin/Javalin.java
- src/main/java/io/javalin/core/util/JettyServerUtil.kt
- src/test/java/io/javalin/TestCustomJetty.kt
- src/test/java/io/javalin/TestWebSocket.kt
@tipsy #472 
I've added the setter as I think you had in mind. Haven't really written Java/Kotlin at all before so let me know if you'd like this done differently.
The .initialize call got quite long with the extra variable, so I multi-lined it. Happy to revert that if you prefer.
As far as the test is concerned, I let me know if you have any suggestions on how it was implemented. I tend to lean on mocking libraries pretty heavily so I'm somewhat lost without them :) I put it in the TestWebsocket file in order to have access to the util types in it.
> Add support for custom websocket servlet factory

- src/main/java/io/javalin/Context.kt
- src/main/java/io/javalin/validation/JavalinValidation.kt
- src/main/java/io/javalin/validation/Validator.kt
- src/test/java/io/javalin/validation/TestValidation.kt
- src/test/java/io/javalin/validation/TestValidation_Java.java
> [core] Rework validation setup

- src/main/java/io/javalin/Javalin.java
- src/main/java/io/javalin/_DataClasses.kt
- src/main/java/io/javalin/core/EventAttacher.java
- src/main/java/io/javalin/core/EventManager.kt
- src/main/java/io/javalin/core/util/RouteOverviewUtil.kt
- src/test/java/io/javalin/TestLifecycleEvents.kt
```
app.on.serverStarting {  }
app.on.serverStarted {  }
app.on.serverStopping {  }
app.on.serverStopping {  }
app.on.serverStopping {  }
app.on.serverStopped {  }
app.on.handlerAdded { handlerMetaInfo -> }
```
> [events] Create events-attacher class to handle public api for events

- src/main/java/io/javalin/core/JavalinWsServlet.kt
- src/main/java/io/javalin/websocket/WsContext.kt
- src/main/java/io/javalin/websocket/WsPathMatcher.kt
- Move path-param and matched-path to WsServlet setup
- Add upgradeCtx field to WsContext to avoid code duplication
> [websocket] Misc refactoring and cleanup

- pom.xml
- src/main/java/io/javalin/Javalin.java
- src/main/java/io/javalin/apibuilder/ApiBuilder.java
- src/main/java/io/javalin/apibuilder/CrudHandler.kt
- src/main/java/io/javalin/core/JavalinConfig.java
- src/main/java/io/javalin/core/PathParser.kt
- src/main/java/io/javalin/plugin/openapi/CreateBaseConfiguration.java
- src/main/java/io/javalin/plugin/openapi/JavalinOpenApi.kt
- src/main/java/io/javalin/plugin/openapi/OpenApiHandler.kt
- src/main/java/io/javalin/plugin/openapi/OpenApiOptions.kt
- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedContent.kt
- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedCrudHandler.kt
- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedHandler.kt
- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedParameter.kt
- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedRequestBody.kt
- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedResponse.kt
- src/main/java/io/javalin/plugin/openapi/dsl/OpenApiBuilder.kt
- src/main/java/io/javalin/plugin/openapi/dsl/OpenApiCrudHandlerDocumentation.kt
- src/main/java/io/javalin/plugin/openapi/dsl/OpenApiDocumentation.kt
- src/main/java/io/javalin/plugin/openapi/dsl/OpenApiUpdater.kt
- src/main/java/io/javalin/plugin/openapi/dsl/extractDocumentation.kt
- src/main/java/io/javalin/plugin/openapi/dsl/openApiBuilderDSL.kt
- src/main/java/io/javalin/plugin/openapi/dsl/openApiUpdaterDSL.kt
- src/main/java/io/javalin/plugin/openapi/external/KotlinOpenApiDsl.kt
- src/test/java/io/javalin/openapi/TestOpenApi.kt
- src/test/java/io/javalin/openapi/json.kt
This PR contains the core and the DSL of the open api schema generation.
The annotation api will be a separate PR.
For more details please refer to the original PR (#568)
> [openapi] Add OpenAPI schema generation by dsl (#254)

- src/main/java/io/javalin/plugin/openapi/JavalinOpenApi.kt
- src/main/java/io/javalin/plugin/openapi/OpenApiOptions.kt
- src/main/java/io/javalin/plugin/openapi/annotations/AnnotationApi.kt
- src/main/java/io/javalin/plugin/openapi/annotations/AnnotationApiMapping.kt
- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedContent.kt
- src/main/java/io/javalin/plugin/openapi/dsl/OpenApiBuilder.kt
- src/main/java/io/javalin/plugin/openapi/dsl/extractDocumentation.kt
- src/test/java/io/javalin/openapi/TestOpenApiAnnotations.kt
- src/test/java/io/javalin/openapi/TestOpenApiAnnotations_Java.java
Add an api to define the OpenApi documentation with annotations.
> [openapi] add annotation api (#254)

- src/main/java/io/javalin/core/JavalinConfig.java
- src/main/java/io/javalin/core/JavalinServer.kt
- src/test/java/io/javalin/TestConfiguration.kt
- src/test/java/io/javalin/TestConfigureServletContextHandler.kt
- src/test/java/io/javalin/TestEventListener.kt
I created the possiblity to add event listeners (like HttpSessionListener or ServletContextListener) to Javalin's ServletContextHandler via the JavalinConfig object.
> Adding event listeners to ServletContextListener

- src/main/java/io/javalin/core/JavalinConfig.java
solves #606, changing setter methods to return this in order to achieve fluent builder.
> [core] changing JavalinConfig object builder to be fluent

- src/main/java/io/javalin/http/Context.kt
- src/main/java/io/javalin/plugin/rendering/FileRenderer.java
- src/main/java/io/javalin/plugin/rendering/JavalinRenderer.kt
- src/main/java/io/javalin/plugin/rendering/markdown/Commonmark.kt
- src/main/java/io/javalin/plugin/rendering/template/JavalinFreemarker.kt
- src/main/java/io/javalin/plugin/rendering/template/JavalinJtwig.kt
- src/main/java/io/javalin/plugin/rendering/template/JavalinMustache.kt
- src/main/java/io/javalin/plugin/rendering/template/JavalinPebble.kt
- src/main/java/io/javalin/plugin/rendering/template/JavalinThymeleaf.kt
- src/main/java/io/javalin/plugin/rendering/template/JavalinVelocity.kt
- src/test/java/io/javalin/TestTemplates.kt
- src/test/resources/templates/thymeleaf/testUrls.html
> Fix thymeleaf templates support

- pom.xml
- src/main/java/io/javalin/core/util/OptionalDependency.kt
Another update of swagger-ui, fixing a security issue.
See https://github.com/swagger-api/swagger-ui/releases/tag/v3.22.2
> Swagger ui update

- src/main/java/io/javalin/plugin/openapi/OpenApiOptions.kt
- src/main/java/io/javalin/plugin/openapi/jackson/JacksonToJsonMapper.kt
- src/main/java/io/javalin/plugin/openapi/utils/LazyDefaultValue.kt
- src/test/java/io/javalin/openapi/utils/LazyDefaultValueTest.kt
> [openapi] do not create defaults if overriden

- src/main/java/io/javalin/core/util/LogUtil.kt
- src/test/java/io/javalin/TestLogging.kt
> [core] support binary output in dev logging

- src/test/java/io/javalin/performance/SimpleAsyncTest.java
- src/test/java/io/javalin/performance/SimplePerformanceTest.java
Some minor changes that may be of use to the project in the future. 
- Renamed two of the test cases with better intent
_Note: I only modified Java classes, since I am not really familiar with Kotlin. But if this kind of pull request or changes seems good to go, I can learn kotlin and check the other classes to see if there may be further optimizations that I can do_
> Rename Stupid prefixed tests to Simple

- pom.xml
- src/main/java/io/javalin/core/compression/Brotli.kt
- src/main/java/io/javalin/core/util/OptionalDependency.kt
Temporary fix for issue #674, until we can fork, repackage and upload jBrotli to maven central
> Make Brotli Optional #674

- src/main/java/io/javalin/core/compression/Brotli.kt
- src/main/java/io/javalin/core/compression/Gzip.kt
- src/main/java/io/javalin/http/JavalinResponseWrapper.kt
- src/main/java/io/javalin/http/staticfiles/JettyResourceHandler.kt
- src/test/java/io/javalin/TestCompression.kt
> 671 fix static files v2

- src/main/java/io/javalin/plugin/openapi/dsl/OpenApiDocumentation.kt
- src/main/java/io/javalin/plugin/openapi/dsl/extractDocumentation.kt
- src/main/java/io/javalin/plugin/openapi/dsl/openApiBuilderDsl.kt
- src/test/java/io/javalin/openapi/TestOpenApi.kt
- src/test/java/io/javalin/openapi/json.kt
> [openapi] Apply defaults before the other documentation

- src/main/java/io/javalin/plugin/rendering/vue/JavalinVue.kt
- src/test/java/io/javalin/TestJavalinVue.kt
This solves the problem where the root vue directory is external, but
not in it's default location.
Closes #706.
Code by @tipsy.
Not sure what an appropriate automated test would be.
> Allow setting vueDirPath for JavalinVue

- pom.xml
- src/main/java/io/javalin/core/util/OptionalDependency.kt
Hi,
I've just created a new release of kotlin-openapi3-dsl, since you are using it I thought it would be nice to just notify you.
> update kotlin-openapi3-dsl dependency to 0.20.2

- src/main/java/io/javalin/plugin/openapi/annotations/AnnotationApi.kt
- src/main/java/io/javalin/plugin/openapi/dsl/extractDocumentation.kt
- src/test/java/io/javalin/TestLogging.kt
- src/test/java/io/javalin/TestWebBrowser.kt
- src/test/java/io/javalin/misc/TestLoggingUtil.kt
- src/test/java/io/javalin/openapi/TestOpenApiAnnotations.kt
- src/test/java/io/javalin/openapi/TestOpenApiAnnotations_Java.java
> [openapi] show warning if path is incorrectly defined

- src/main/java/io/javalin/core/util/ReflectionUtil.kt
- src/main/java/io/javalin/plugin/openapi/dsl/OpenApiBuilder.kt
- src/main/java/io/javalin/plugin/openapi/dsl/extractDocumentation.kt
- src/test/java/io/javalin/openapi/TestOpenApi.kt
- src/test/java/io/javalin/openapi/TestOpenApiAnnotations.kt
- src/test/java/io/javalin/openapi/TestOpenApiAnnotations_Java.java
> [openapi] fix reflection errors with extended classes

- src/main/java/io/javalin/http/Context.kt
- src/test/java/io/javalin/TestRequest.kt
- src/test/java/io/javalin/misc/HttpUtil.kt
> [core] request header validator

- src/main/java/io/javalin/plugin/openapi/OpenApiHandler.kt
- src/main/java/io/javalin/plugin/openapi/OpenApiOptions.kt
- src/test/java/io/javalin/openapi/TestOpenApi.kt
- src/test/java/io/javalin/openapi/TestOpenApiAnnotations.kt
- src/test/java/io/javalin/openapi/json.kt
> Open api plugin ignore paths

- src/main/java/io/javalin/plugin/openapi/JavalinOpenApi.kt
- src/main/java/io/javalin/plugin/openapi/OpenApiHandler.kt
- src/main/java/io/javalin/plugin/openapi/OpenApiOptions.kt
- src/main/java/io/javalin/plugin/openapi/dsl/openApiBuilderDsl.kt
- src/test/java/io/javalin/openapi/TestOpenApi.kt
- src/test/java/io/javalin/openapi/json.kt
See #722 
@TobiasWalle I don't know whether I added the code on the intended places,
I'm a bit confused about how the OpenApi generation works
> Implemented setDocumentation in OpenApi Plugin

- src/main/java/io/javalin/http/UploadedFile.kt
- src/main/java/io/javalin/http/util/MultipartUtil.kt
Hiya!
This is from our discussion [here](https://github.com/RyanSusana/elepy/commit/92388f54d20ffe6efc406a75a65bba05f7b26397#commitcomment-35233933) @tipsy 
I didn't realize that contentLength was the filesize.
You might want to consider changing contentLength to a long(breaking change), because files can be huge!
This also gets covered by the Multipart tests 😄
> Improved MultipartFileUpload a small bit

- src/main/java/io/javalin/http/util/ContextUtil.kt
- src/test/java/io/javalin/TestRequest.kt
> [context] handling equal sign in query parameters values

- src/main/java/io/javalin/plugin/openapi/annotations/AnnotationApi.kt
- src/main/java/io/javalin/plugin/openapi/annotations/AnnotationApiMapping.kt
- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedFormParameter.kt
- src/main/java/io/javalin/plugin/openapi/dsl/OpenApiDocumentation.kt
- src/main/java/io/javalin/plugin/openapi/dsl/openApiBuilderDsl.kt
- src/test/java/io/javalin/openapi/TestOpenApi.kt
- src/test/java/io/javalin/openapi/TestOpenApiAnnotations.kt
- src/test/java/io/javalin/openapi/json.kt
Adds a simple method to add formData parameter. The method matches the Javalin Api.
Resolves #783
> Openapi form param

- src/main/java/io/javalin/plugin/openapi/annotations/AnnotationApi.kt
> Warn about documented path-params missing in path only if there are some.

- src/main/java/io/javalin/http/Context.kt
Add error log for deserialization failures to show original exception information.
> Add error log for deserialization failures to show original exception information.

- src/main/java/io/javalin/plugin/openapi/JavalinOpenApi.kt
- src/main/java/io/javalin/plugin/openapi/OpenApiOptions.kt
- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedContent.kt
- src/main/java/io/javalin/plugin/openapi/external/KotlinOpenApiDsl.kt
- src/main/java/io/javalin/plugin/openapi/jackson/JacksonModelConverterFactory.kt
- src/main/java/io/javalin/plugin/openapi/jackson/JacksonToJsonMapper.kt
- src/main/java/io/javalin/plugin/openapi/jackson/JavalinModelResolver.kt
- src/test/java/io/javalin/openapi/TestOpenApi.kt
- src/test/java/io/javalin/openapi/json.kt
> [openapi] fix Instant serialization

- src/main/java/io/javalin/core/JavalinConfig.java
- src/main/java/io/javalin/http/SinglePageHandler.kt
- src/test/java/io/javalin/TestSinglePageMode.kt
Issue https://github.com/tipsy/javalin/issues/812
> Support single page custom handlers

- src/main/java/io/javalin/Javalin.java
Mention how to start the server on a random port in the Javadoc as well.
> Document that Javalin.start() uses the default (and not random port)

- src/main/java/io/javalin/http/Context.kt
- src/main/java/io/javalin/http/util/ContextUtil.kt
Resolves: #837
Signed-off-by: Thibault Meyer <meyer.thibault@gmail.com>
> Use request encoding charset to URL decode form params & parse body

- src/main/java/io/javalin/http/Context.kt
- src/test/java/io/javalin/TestResponse.kt
- src/test/kotlin/io/javalin/examples/HelloWorldImages.kt
also, a new web server demo that returns solid-colored image rectangles
> created new ctx.result(byte[]) method

- src/main/java/io/javalin/plugin/openapi/annotations/AnnotationApi.kt
- src/main/java/io/javalin/plugin/openapi/annotations/AnnotationApiMapping.kt
- src/test/java/io/javalin/openapi/TestOpenApi.kt
- src/test/java/io/javalin/openapi/TestOpenApiAnnotations.kt
- src/test/java/io/javalin/openapi/json.kt
> [openapi] add security for individual operator

- src/main/java/io/javalin/plugin/json/JavalinJackson.kt
- src/main/java/io/javalin/plugin/rendering/markdown/Commonmark.kt
- src/main/java/io/javalin/plugin/rendering/template/JavalinFreemarker.kt
- src/main/java/io/javalin/plugin/rendering/template/JavalinJtwig.kt
- src/main/java/io/javalin/plugin/rendering/template/JavalinMustache.kt
- src/main/java/io/javalin/plugin/rendering/template/JavalinPebble.kt
- src/main/java/io/javalin/plugin/rendering/template/JavalinThymeleaf.kt
- src/main/java/io/javalin/plugin/rendering/template/JavalinVelocity.kt
This path protects the lazy initialization of default renderers.
> Add locking around renderers lazy initialization

- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedContent.kt
- src/main/java/io/javalin/plugin/openapi/dsl/DocumentedParameter.kt
- src/main/java/io/javalin/plugin/openapi/dsl/OpenApiDocumentation.kt
- src/test/java/io/javalin/openapi/TestOpenApiAnnotations.kt
- src/test/java/io/javalin/openapi/json.kt
> [openapi] Add beans in query params to components

- src/main/java/io/javalin/http/util/SeekableWriter.kt
> Set content type in missing case in SeekableWriter

- pom.xml
- src/main/java/io/javalin/core/util/OptionalDependency.kt
There was recently another Bugfix release of swagger-core
> Bumped swagger-core

- javalin/src/main/java/io/javalin/core/util/Util.kt
Use `java.util.ServiceLoader` to check if slf4j implementation is loaded.
See #922.
> fix optional logging dependencies message

- javalin/src/main/java/io/javalin/apibuilder/ApiBuilder.java
- javalin/src/main/java/io/javalin/apibuilder/CrudHandler.kt
- javalin/src/main/java/io/javalin/plugin/openapi/dsl/DocumentedCrudHandler.kt
- javalin/src/main/java/io/javalin/plugin/openapi/dsl/OpenApiBuilder.kt
- javalin/src/main/java/io/javalin/plugin/openapi/dsl/extractDocumentation.kt
This PR remove OpenAPI usage in ApiBuilder, to prepare the creation of OpenAPI module
> [multimodule] decrease coupling with OpenAPI

- javalin-openapi/pom.xml
- javalin/pom.xml
- pom.xml
- Rename parent to include "(parent)"
- Remove duplicate dependency (logger)
- Move exclusions to dependencyManagement section
- Include openapi-dsl in openapi module
> [multi-module] Minor cleanup

- .github/workflows/detekt-hint.yaml
- config/detekt-hint-config.yml
> Integration with detekt-hint

- javalin/src/main/java/io/javalin/core/JavalinConfig.java
- javalin/src/main/java/io/javalin/core/util/Util.kt
- javalin/src/main/java/io/javalin/http/staticfiles/JettyResourceHandler.kt
- javalin/src/main/java/io/javalin/http/staticfiles/PrecompressingResourceHandler.kt
- javalin/src/test/java/io/javalin/TestStaticFiles.kt
For issue #892 and PR #932.
I add a precompressStaticFiles config  and two parameters in JettyResourceHandler's construct.
> Add precompression handler

- javalin-openapi/src/main/java/io/javalin/plugin/openapi/dsl/extractDocumentation.kt
- javalin-openapi/src/test/java/io/javalin/plugin/openapi/TestOpenApiAnnotations_Java.java
- javalin-openapi/src/test/java/io/javalin/plugin/openapi/json.kt
- javalin/src/main/java/io/javalin/core/util/ReflectionUtil.kt
* addresses issue #956 (OpenAPI annotations of Java non-static class fields)
* added unit-tests for various class/field-type combinations
Hope others find this also useful. Enjoy!
> fixes/upgrades OpenAPI field annotation

- javalin/pom.xml
- javalin/src/main/java/io/javalin/core/util/OptionalDependency.kt
- javalin/src/main/java/io/javalin/plugin/rendering/JavalinRenderer.kt
- javalin/src/main/java/io/javalin/plugin/rendering/template/JavalinJte.kt
- javalin/src/test/java/io/javalin/TestTemplates.kt
- javalin/src/test/resources/templates/jte/multiple-params.jte
- javalin/src/test/resources/templates/jte/test.jte
- pom.xml
Hi @tipsy, this is a first draft of a jte integration for Javalin!
I went with solution 1, and added a "jte" key to the model map, which is a bit hacky.
Changing the model parameter to `Any`, would be nicer for jte, but require a change to the interface. Not sure if you would want to do that.
Maybe there's an even better solution I can't think of right now?
> Initial insert of jte integration

- javalin/src/main/java/io/javalin/core/security/SecurityUtil.kt
- javalin/src/main/java/io/javalin/core/util/CorsPlugin.kt
- javalin/src/main/java/io/javalin/http/JavalinServlet.kt
- javalin/src/main/java/io/javalin/http/util/CorsUtil.kt
- javalin/src/test/java/io/javalin/TestCors.kt
> Allowing for the CORS plugin and OPTIONS endpoints to coexist

- javalin-openapi/src/main/java/io/javalin/plugin/openapi/OpenApiHandler.kt
- javalin-openapi/src/main/java/io/javalin/plugin/openapi/dsl/openApiBuilderDsl.kt
- javalin/src/main/java/io/javalin/core/JavalinConfig.java
- javalin/src/main/java/io/javalin/core/PathParser.kt
- javalin/src/main/java/io/javalin/http/JavalinServlet.kt
- javalin/src/main/java/io/javalin/http/PathMatcher.kt
- javalin/src/main/java/io/javalin/http/util/RedirectToLowercasePathPlugin.kt
- javalin/src/main/java/io/javalin/websocket/JavalinWsServlet.kt
- javalin/src/main/java/io/javalin/websocket/WsPathMatcher.kt
- javalin/src/test/java/io/javalin/TestTrailingSlashes.kt
- javalin/src/test/java/io/javalin/performance/RouteMatcherPerformanceTest.kt
Currently true by default, maybe false as it's seem to follow the uri spec (https://tools.ietf.org/html/rfc3986#section-6.2.4)
(@tipsy May check how it's handle in OpenApiHandler, can't find config here, and set param as true in hard)
> Added ignoreTrailingSlashes options (FR #1050)

- javalin/src/main/java/io/javalin/http/staticfiles/PrecompressingResourceHandler.kt
> [static-files] Use ConcurrentHashMap instead of HashMap

- javalin/src/main/java/io/javalin/core/JavalinConfig.java
- javalin/src/main/java/io/javalin/http/CachedRequestWrapper.kt
- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/main/java/io/javalin/http/JavalinServlet.kt
- javalin/src/main/java/io/javalin/http/RequestWrapper.kt
- javalin/src/test/java/io/javalin/TestBodyIsCreatedOnce.kt
- javalin/src/test/java/io/javalin/TestBodyReading.kt
- javalin/src/test/java/io/javalin/TestMaxRequestSize.kt
- javalin/src/test/java/io/javalin/TestRequestCache.kt
> Support multiple calls to body

- pom.xml
in 4.8.66 the pom.xml is invalid because of
a not well-formed comment at line 235
Change-Id: Ic1aa209d67866ecd35575fcb550c8d1a10bbbb6d
> [deps] bump classgraph

- javalin-openapi/src/main/java/io/javalin/plugin/openapi/dsl/DocumentedHandler.kt
- javalin-openapi/src/test/java/io/javalin/plugin/openapi/TestDocumentedHandler.java
> opens DocumentedHandler to allow for class inheritance

- javalin/src/main/java/io/javalin/http/JavalinServlet.kt
- javalin/src/test/java/io/javalin/TestFuture.kt
> Handling exceptions thrown while writing the result stream on asynchronous requests

- javalin-openapi/src/main/java/io/javalin/plugin/openapi/OpenApiHandler.kt
- javalin-openapi/src/main/java/io/javalin/plugin/openapi/OpenApiModelModifier.kt
- javalin-openapi/src/main/java/io/javalin/plugin/openapi/OpenApiOptions.kt
- javalin-openapi/src/test/java/io/javalin/plugin/openapi/TestOpenApi.kt
- javalin-openapi/src/test/java/io/javalin/plugin/openapi/json.kt
Code to address issue #1205.  This is my first time trying Kotlin, so please let me know if there are better ways to achieve this goal.
> [openapi] Add option to allow modification of OpenAPI model returned.

- javalin/src/main/java/io/javalin/core/util/LogUtil.kt
Reference: https://github.com/tipsy/javalin/issues/1169
> backporting fix for URLDecoder when using 'enableDevLogging'

- javalin/src/main/java/io/javalin/core/util/OptionalDependency.kt
- pom.xml
Tests passed locally when running `mvn clean package` (hope that is all needed)
> Update JTE to 1.10.0

- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/test/java/io/javalin/TestContextHandlerType.java
> Expose HandlerType in Context

- javalin/src/main/java/io/javalin/core/validation/BaseValidator.kt
- javalin/src/main/java/io/javalin/core/validation/BodyValidator.kt
- javalin/src/main/java/io/javalin/core/validation/JavalinValidation.kt
- javalin/src/main/java/io/javalin/core/validation/NullableValidator.kt
- javalin/src/main/java/io/javalin/core/validation/Validator.kt
- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/test/java/io/javalin/TestJson.kt
- javalin/src/test/java/io/javalin/TestValidation.kt
I'm having some difficulty running the tests locally, not entirely sure why. I'm getting a failing test (I think from running Vue tests?), but I'm not able to locate where the error is. Nothing is telling me what failed. That said, this is meant to be a quick example of the API I was considering. I have not added/changed any tests. I would expect them all to pass still, the idea is that the previous API works exactly as it did, no added complexity if you don't use the new overloaded functions. If this seems like a reasonable API I'll be happy to contribute some additional documentation and tests.
> Adding Args to Error Responses

- javalin/src/main/java/io/javalin/Javalin.java
> Fix : Can't bind to port - always reports it's 7000

- .gitignore
- javalin/src/main/java/io/javalin/core/JavalinServer.kt
- javalin/src/main/java/io/javalin/http/JavalinServlet.kt
- javalin/src/test/java/io/javalin/TestServerHeader.kt
#1284 : Disable Default Server Header
> Disable Default Server-header

- javalin/src/main/java/io/javalin/http/HttpCode.kt
- javalin/src/test/java/io/javalin/http/HttpCodeTest.kt
* Associated with https://github.com/tipsy/javalin/issues/1340
> GH-1340 Provide toString() implementation for HttpCode

- javalin/src/main/java/io/javalin/core/JavalinConfig.java
> GH-1347 Preserve order of registered plugins

- javalin/src/main/java/io/javalin/http/JavalinServlet.kt
- javalin/src/test/java/io/javalin/TestFuture.kt
> Cancelling a timed out future.

- javalin/src/main/java/io/javalin/core/JavalinConfig.java
- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/main/java/io/javalin/http/ContextResolver.kt
- javalin/src/test/java/io/javalin/TestConfiguration.kt
Added ContextResolver config options to set  custom implementations for resolving IP & Host.
>  Add ContextResovler config options #1339

- javalin/src/main/java/io/javalin/http/JavalinServlet.kt
Similar issue to the #1385, this time related to the check that allows us to ensure that finishing call was not called twice or even more. I used `AtomicBoolean` to simplify logic rather than wrapping this with some kind of a synchronized & lock based flow - should be enough as it's now just only one call to thread-safe method.
> GH-1385 Make responseStarted variable thread-safe

- javalin/src/test/java/io/javalin/TestLogging.kt
(cherry picked from commit 5abfc9c1ca900a26ae672bfe1502282c879a0748)
> [tests] Fix flaky test on Windows

- javalin/src/main/java/io/javalin/core/validation/BaseValidator.kt
- javalin/src/main/java/io/javalin/core/validation/NullableValidator.kt
- javalin/src/main/java/io/javalin/core/validation/Validator.kt
- javalin/src/test/java/io/javalin/TestValidation.kt
Second attempt of solving issue #1393. This time without extending class hierarchy.
> issue #1393 Create validator for typed value

- javalin/src/main/java/io/javalin/core/LoomUtil.kt
Enables support for running Javalin on the latest Loom preview builds.
> GH-1437 Update LoomUtil to reflect latest API changes

- javalin/src/main/java/io/javalin/http/Context.kt
This PR fixes #1392. See my comments on the issue.
> make sure json character encoding is always utf-8

- javalin/pom.xml
- javalin/src/main/java/io/javalin/Javalin.java
- javalin/src/test/java/io/javalin/TestClose.kt
- javalin/src/test/java/io/javalin/TestClose_Java.java
- javalin/src/test/java/io/javalin/testing/TestUtil.java
Hi Tipsy,
First, thank you so much for creating and maintaining this wonderful project.
This PR simply makes Javalin implement AutoClosable so that it's compatible with try-with-resources. See tests for examples. Please let me know your thoughts and about any improvements I can make. Did my best to follow existing code style.
Thanks.
> Enhance Javalin to support try with resources

- javalin/src/main/java/io/javalin/core/PathParser.kt
- javalin/src/test/java/io/javalin/TestRouting.kt
> Allow literal colons in paths

- javalin-bundle/pom.xml
- javalin/src/main/java/io/javalin/core/util/OptionalDependency.kt
- javalin/src/main/java/io/javalin/core/util/Util.kt
- javalin/src/main/java/io/javalin/plugin/json/JavalinJackson.kt
- javalin/src/test/java/io/javalin/TestJson.kt
> [jackson] Register java time module if exist

- javalin/src/main/java/io/javalin/core/util/Header.kt
This is helpful to get real ip when using proxies like Apache or Nginx.
> Added Header.X_FORWARDED_FOR constant.

- javalin/src/main/java/io/javalin/http/ContentType.kt
Related to discussion on Discord
> Convert .jpg extension to alias of JPEG type

- javalin/src/main/java/io/javalin/plugin/rendering/vue/JavalinVue.kt
Context: https://twitter.com/dzikoysk/status/1490053963827269632
> [fix] Fix small resource leak in JavalinVue class

- javalin/src/test/java/io/javalin/TestWebSocket.kt
> [fix] Fix nondeterministic test case in TestWebSocket class

- javalin/src/test/java/io/javalin/TestWebBrowser.kt
> [fix] Fix nondeterministic test case in TestWebBrowser class

- pom.xml
> GH-1488 Bump selenium & webdriver to next major versions

- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/main/java/io/javalin/http/ContextResolver.kt
- javalin/src/main/java/io/javalin/http/JavalinServletHandler.kt
- javalin/src/test/java/io/javalin/TestFuture.kt
> [config] Add future callback to context resolvers

- javalin-openapi/src/main/java/io/javalin/plugin/openapi/annotations/AnnotationApi.kt
- javalin-openapi/src/test/java/io/javalin/plugin/openapi/TestOpenApiAnnotations_Java.java
> Use PathParser to produce OpenApi Warnings

- javalin/src/test/java/io/javalin/TestRouting.kt
- javalin/src/test/java/io/javalin/testing/HttpUtil.kt
- pom.xml
Related: ~ https://github.com/Kong/unirest-java/issues/439
> [tests] Bump Unirest to 3.13.8

- javalin/src/main/java/io/javalin/core/validation/JavalinValidation.kt
- javalin/src/test/java/io/javalin/TestValidation.kt
> Allow collecting errors from a NullableValidator

- javalin/src/main/java/io/javalin/core/validation/BaseValidator.kt
- javalin/src/main/java/io/javalin/core/validation/BodyValidator.kt
- javalin/src/main/java/io/javalin/core/validation/Validator.kt
- javalin/src/test/java/io/javalin/TestValidation.kt
- javalin/src/test/java/io/javalin/TestValidation_Java.java
> GH-1534 Add getOrThrow method to BaseValidator

- javalin-openapi/src/main/java/io/javalin/plugin/openapi/jackson/JavalinModelResolver.kt
- javalin-openapi/src/test/java/io/javalin/plugin/openapi/TestOpenApi.kt
Error in Openapi with custom annotations (see regression test)
> [openapi] Fix openapi custom annotation handling

- .github/workflows/publish-snapshots.yml
- pom.xml
> [dsitribution] Publish snapshots on CI to maven.reposilite.com/snapshots

- javalin/src/main/java/io/javalin/http/util/ContextUtil.kt
- javalin/src/test/java/io/javalin/TestRequest.kt
Related to discussion with CocaCola on Discord:
~ https://discord.com/channels/804862058528505896/805106384977920040/989277505879957575
> [cleanup] Simplify logic in ContextUtil#getBasicAuthCredentials

- .github/workflows/publish-snapshots.yml
* https://github.com/javalin/javalin/issues/1570#issuecomment-1182271412
> [distribution] Publish snapshots with `sonatype-oss-release` profile

- .github/workflows/publish-snapshots.yml
- pom.xml
> [distribution] Bump plugins to latest versions and provide dedicated profile for snapshot distribution

- javalin/src/main/java/io/javalin/util/ConcurrencyUtil.kt
> Fix compatibility with latest Loom version.

- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/main/java/io/javalin/http/HandlerType.kt
- javalin/src/main/java/io/javalin/http/JavalinResponseWrapper.kt
- javalin/src/main/java/io/javalin/http/JavalinServlet.kt
- javalin/src/main/java/io/javalin/http/JavalinServletHandler.kt
- javalin/src/main/java/io/javalin/plugin/CorsPlugin.kt
- javalin/src/main/java/io/javalin/plugin/DevLoggerPlugin.kt
- javalin/src/main/java/io/javalin/plugin/RedirectToLowercasePathPlugin.kt
> [context] Return `HandlerType` from `ctx.method()` instead of String

- javalin/src/main/java/io/javalin/util/OptionalDependency.kt
- pom.xml
Should be merged before 
* https://github.com/javalin/javalin/pull/1670
> [dependencies] Bump Jackson to 2.13.4

- javalin/src/main/java/io/javalin/json/JavalinJackson.kt
- javalin/src/main/java/io/javalin/util/OptionalDependency.kt
* https://github.com/FasterXML/jackson-datatypes-collections/blob/2.14/eclipse-collections/src/main/java/com/fasterxml/jackson/datatype/eclipsecollections/EclipseCollectionsModule.java
> [json-mapper] Support eclipse-collections out of the box (Resolve #1668)

- .github/workflows/main.yml
- javalin/src/main/java/io/javalin/core/LoomUtil.kt
- javalin/src/main/java/io/javalin/jetty/JettyUtil.kt
- javalin/src/main/java/io/javalin/plugin/json/PipedStreamUtil.kt
> [loom] Make Loom implementation work with JDK 19

- javalin/src/main/java/io/javalin/core/LoomUtil.kt
Backporting changes from 5.0.0
> [loom] Try to get executor instead of just checking for existence

- javalin/src/main/java/io/javalin/util/ConcurrencyUtil.kt
This PR changes the Virtual Thread components in `ConcurrencyUtil.kt` to use the `java.lang.invoke` MethodHandle API instead of the Java Reflection API. In situations like this, where a specific set of methods is called over and over again, this should bring a performance benefit. Furthermore, there is an improvement that extracts the method lookup to a companion object, which saves some work in each invocation.
In an ideal world, these MethodHandles would use `invokeExact` instead of `invoke` to get closer to the performance of calling the methods directly, but for that to work this library would have to be compiled against Java 19.
Overall, this PR may be useful as a temporary performance improvement over the current state while multi-release jars are still being discussed as an option.
> Migrate to using MethodHandles for project loom support

- javalin/src/main/java/io/javalin/util/OptionalDependency.kt
- pom.xml
> Update Slf4j version

- javalin/src/main/java/io/javalin/http/Context.kt
> Add async overload taking Runnable as parameter

- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/main/java/io/javalin/http/util/AsyncUtil.kt
- javalin/src/main/java/io/javalin/util/function/ThrowingRunnable.java
- javalin/src/main/java/io/javalin/util/function/ThrowingSupplier.java
- javalin/src/test/java/io/javalin/TestFuture.kt
- javalin/src/test/java/io/javalin/examples/HelloWorldAsync.java
- javalin/src/test/java/io/javalin/examples/HelloWorldFuture.java
> [async] Fix `ctx.async` interopability with Java (Fix #1703)

- javalin/src/main/java/io/javalin/http/servlet/DefaultTasks.kt
- javalin/src/test/java/io/javalin/TestFilters.kt
> [access-manager] Remove untested and incorrect submitTask wrapper

- javalin/src/main/java/io/javalin/http/servlet/DefaultTasks.kt
- javalin/src/test/java/io/javalin/TestAccessManager.kt
> [access-manager] Update layer test for access manager

- javalin/src/main/java/io/javalin/plugin/bundled/CorsPlugin.kt
- javalin/src/test/java/io/javalin/TestCors.kt
> [cors] Support 405 status code (fixes #1718)

- javalin-testtools/src/main/java/io/javalin/testtools/HttpClient.kt
> backport changes to testtools localhost resolution

- javalin/src/main/java/io/javalin/util/ConcurrencyUtil.kt
- javalin/src/test/java/io/javalin/TestCustomJetty.kt
This change makes API more consistent and improves visibility of useful methods + hides implementation details for both, Kotlin and Java users.
> [utils] Improve API & its visibility exposed by ConcurrencyUtil class

- javalin/src/main/java/io/javalin/compression/CompressedStream.kt
- javalin/src/test/java/io/javalin/TestCompression.kt
> Fix precompress return wrong data

- javalin/src/main/java/io/javalin/http/servlet/JavalinServlet.kt
- javalin/src/main/java/io/javalin/http/servlet/JavalinServletContext.kt
> [servlet] Request `ctx.outputStream()` only if there's result stream to write

- javalin/src/main/java/io/javalin/http/Context.kt
Added the appropriate namespacing for javadoc annotations in Context.
Fixes #1768!
> Fixed javadoc error in Context

- javalin/src/test/java/io/javalin/TestResponse.kt
fixes #1771 
The volatile boolean tracking the input stream's closed status intermittently fails on some platforms, likely due to a race condition. Switching over to a `CountDownLatch`
> Fix flaky Seekable test

- pom.xml
> [maven] Fix dependencies visibility in parent pom

- javalin/pom.xml
- javalin/src/test/java/io/javalin/TestUnixSocketConnector.kt
- pom.xml
> Update Unix socket test for Jetty 11

- javalin/src/main/java/io/javalin/http/ContentType.kt
> [content-type] Change deprecation level of `APPLICATION_JS` to `WARNING`

- javalin/src/main/java/io/javalin/config/JavaLangErrorHandler.java
- javalin/src/main/java/io/javalin/config/PrivateConfig.kt
- javalin/src/main/java/io/javalin/http/servlet/ExceptionMapper.kt
- javalin/src/test/java/io/javalin/TestExceptionMapper.kt
> Add javaLangErrorHandler to pvt config

- javalin/src/test/java/io/javalin/TestWebBrowser.kt
- javalin/src/test/java/io/javalin/javalinvue/TestJavalinVueBrowser.kt
- pom.xml
Fix chrome driver for failing tests
> Javalin 4x

- javalin/src/main/java/io/javalin/websocket/WsContext.kt
> Add method level docs to `WsContext`

- javalin/src/main/java/io/javalin/plugin/bundled/CorsPlugin.kt
- javalin/src/test/java/io/javalin/TestCors.kt
Closes #1876 
Spec: https://fetch.spec.whatwg.org/#http-access-control-max-age
> [corsplugin] Add `Access-Control-Max-Age` support to CorsPlugin

- javalin/src/main/java/io/javalin/json/JavalinGson.kt
- javalin/src/test/java/io/javalin/TestJavalinGson.kt
OutputStreamWriter requires flush
> [gson] Fix `JavalinGson#toJsonStream`

- javalin/src/test/java/io/javalin/TestWebBrowser.kt
- javalin/src/test/java/io/javalin/javalinvue/TestJavalinVueBrowser.kt
- pom.xml
Closes #1875, don't know if it will fix it
- Bump test dep versions
- Use a [fresh browser per test](https://www.selenium.dev/documentation/test_practices/encouraged/fresh_browser_per_test/)
- Add fixes to the `TestWebBrowser` test class
- Use: https://bonigarcia.dev/selenium-jupiter/
> Improve Vue tests using selenium

- javalin/src/main/java/io/javalin/config/RoutingConfig.kt
- javalin/src/main/java/io/javalin/plugin/bundled/RedirectToLowercasePathPlugin.kt
- javalin/src/main/java/io/javalin/routing/PathParser.kt
- javalin/src/test/java/io/javalin/TestRouting.kt
Discussed on discord
I'm missing a test for path params.
> Add case insensitive matching

- javalin/src/main/java/io/javalin/vue/VuePathMaster.kt
project sampling the problem [here](https://github.com/sombriks/sample-jdbi-javalin), relates to #1904
> small fix to solve jar resource classpath scanning issue for vue plugin

- javalin/src/main/java/io/javalin/jetty/JettyPrecompressingResourceHandler.kt
> Add method to clear the cache of pre-compressed files

- .editorconfig
- javalin-micrometer/src/main/java/io/javalin/micrometer/MicrometerPlugin.kt
- javalin/src/main/java/io/javalin/config/JavalinConfig.kt
- javalin/src/main/java/io/javalin/config/JettyConfig.kt
- javalin/src/main/java/io/javalin/config/PrivateConfig.kt
- javalin/src/main/java/io/javalin/http/servlet/JavalinServletContext.kt
- javalin/src/main/java/io/javalin/jetty/JavalinJettyServlet.kt
- javalin/src/main/java/io/javalin/jetty/JettyResourceHandler.kt
- javalin/src/main/java/io/javalin/jetty/JettyServer.kt
- javalin/src/main/java/io/javalin/util/ConcurrencyUtil.kt
- javalin/src/test/java/io/javalin/TestConfiguration.kt
- javalin/src/test/java/io/javalin/TestConfigureServletContextHandler.kt
- javalin/src/test/java/io/javalin/TestCustomJetty.kt
- javalin/src/test/java/io/javalin/TestCustomJettyHttpConfiguration.kt
- javalin/src/test/java/io/javalin/TestCustomRequestLifecycle.kt
- javalin/src/test/java/io/javalin/TestGracefulShutdown.java
- javalin/src/test/java/io/javalin/TestUnixSocketConnector.kt
- javalin/src/test/java/io/javalin/TestWebSocket.kt
- javalin/src/test/java/io/javalin/examples/HelloWorldSecure.java
- javalin/src/test/java/io/javalin/examples/HelloWorldServlet.java
- javalin/src/test/java/io/javalin/performance/SimpleAsyncTest.java
- javalin/src/test/java/io/javalin/staticfiles/TestStaticFiles.kt
- javalin/src/test/kotlin/io/javalin/examples/AdvancedServerSentEvent.kt
- javalin/src/test/kotlin/io/javalin/examples/HelloWorldSecure.kt
Closes #1913 (if merged). Missing tests for the new methods.
> [jetty] Cleanup Jetty Config 

- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/test/java/io/javalin/TestResponse.kt
> [context] Add removeHeader function

- javalin/src/main/java/io/javalin/http/util/SeekableWriter.kt
- javalin/src/test/java/io/javalin/TestResponse.kt
> Support Content-Length and Accepts-Range when no Range is specified

- javalin/src/main/java/io/javalin/http/servlet/ErrorMapper.kt
- javalin/src/main/java/io/javalin/http/servlet/JavalinServletContext.kt
- javalin/src/main/java/io/javalin/jetty/JettyResourceHandler.kt
- javalin/src/main/java/io/javalin/json/JavalinJackson.kt
- javalin/src/main/java/io/javalin/json/PipedStreamUtil.kt
- javalin/src/main/java/io/javalin/routing/ParserState.kt
- javalin/src/main/java/io/javalin/util/ConcurrencyUtil.kt
- javalin/src/main/java/io/javalin/validation/BaseValidator.kt
- javalin/src/main/java/io/javalin/vue/VueFileInliner.kt
- javalin/src/main/java/io/javalin/vue/VueHandler.kt
- javalin/src/main/java/io/javalin/vue/VuePathMaster.kt
- javalin/src/main/java/io/javalin/websocket/WsAutomaticPing.kt
- javalin/src/main/java/io/javalin/websocket/WsConnection.kt
- javalin/src/main/java/io/javalin/websocket/WsContext.kt
- javalin/src/test/java/io/javalin/TestConcurrencyUtil.kt
Rebased [dzikoysk-playground/javalin:context-sync-loom](https://github.com/dzikoysk-playground/javalin/tree/context-sync-loom) (#1968) on top of master. 
Resolves #1966 on 6.x branch.
> [loom] Introduce javalinLazy to avoid kotlin.lazy/loom issues (6.x)

- javalin-micrometer/src/main/java/io/javalin/micrometer/MicrometerPlugin.kt
- javalin/src/main/java/io/javalin/Javalin.java
- javalin/src/main/java/io/javalin/config/ConfigurableInstance.kt
- javalin/src/main/java/io/javalin/plugin/PluginManager.kt
- javalin/src/main/java/io/javalin/plugin/bundled/RedirectToLowercasePathPlugin.kt
- javalin/src/main/java/io/javalin/router/InternalRouter.kt
- javalin/src/main/java/io/javalin/router/JavalinDefaultRoutingApi.kt
- javalin/src/main/java/io/javalin/security/AccessManager.kt
- javalin/src/test/java/io/javalin/TestAccessManager.kt
- javalin/src/test/java/io/javalin/TestConfiguration.kt
- javalin/src/test/java/io/javalin/TestExceptionMapper.kt
- javalin/src/test/java/io/javalin/TestFuture.kt
- javalin/src/test/java/io/javalin/TestMultipartForms.kt
- javalin/src/test/java/io/javalin/TestRouting.kt
- javalin/src/test/java/io/javalin/TestWebSocket.kt
- javalin/src/test/java/io/javalin/routeoverview/TestRouteOverviewPlugin.kt
- javalin/src/test/java/io/javalin/routeoverview/VisualTest.java
- javalin/src/test/java/io/javalin/staticfiles/TestStaticFiles.kt
Closes https://github.com/javalin/javalin/issues/1975
> [core] Make cfg private and introduce unsafeConfig()

- javalin/src/main/java/io/javalin/plugin/bundled/RouteOverviewPlugin.kt
- javalin/src/main/java/io/javalin/plugin/bundled/RouteOverviewUtil.kt
> [route-overview] Use InternalRouter in RouteOverviewPlugin instead of manual routes tracking

- javalin/src/main/java/io/javalin/config/JavalinConfig.kt
- javalin/src/main/java/io/javalin/config/PrivateConfig.kt
- javalin/src/main/java/io/javalin/config/RouterConfig.kt
- javalin/src/main/java/io/javalin/plugin/PluginApi.kt
- javalin/src/main/java/io/javalin/plugin/PluginManager.kt
- javalin/src/test/java/io/javalin/TestLifecycleEvents.kt
- javalin/src/test/java/io/javalin/TestPlugins.kt
- javalin/src/test/java/io/javalin/routeoverview/TestRouteOverviewPlugin.kt
Fixes https://github.com/javalin/javalin/issues/1990, #1991
> [plugins] Fix issue with plugins being registered too late (v2)

- javalin/src/main/java/io/javalin/http/HttpStatus.kt
- javalin/src/test/java/io/javalin/http/HttpStatusCodeTest.kt
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
> [http] Add user-friendly API methods for known HttpStatus code ranges

- javalin/src/main/java/io/javalin/websocket/WsCloseStatus.kt
- javalin/src/main/java/io/javalin/websocket/WsContext.kt
- javalin/src/test/java/io/javalin/TestWebSocket.kt
> [websockets] WebSockets close codes

- javalin/src/main/java/io/javalin/Javalin.java
- javalin/src/main/java/io/javalin/config/JavalinConfig.kt
- javalin/src/main/java/io/javalin/config/JettyConfig.kt
- javalin/src/main/java/io/javalin/jetty/JettyServer.kt
- javalin/src/test/java/io/javalin/TestConfiguration.kt
> [config] Move default port & host configuration to JavalinConfig

- javalin-testtools/pom.xml
- javalin/src/main/java/io/javalin/Javalin.java
- javalin/src/main/java/io/javalin/config/PrivateConfig.kt
- javalin/src/main/java/io/javalin/http/servlet/ServletEntry.kt
- javalin/src/main/java/io/javalin/jetty/JavalinJettyServlet.kt
- javalin/src/main/java/io/javalin/jetty/JettyServer.kt
- javalin/src/main/java/io/javalin/jetty/JettyUtil.kt
- pom.xml
> [websockets] Encapsulate Servlet & Initializer in `ServletEntry`

- javalin/src/main/java/io/javalin/config/JettyConfig.kt
- javalin/src/main/java/io/javalin/config/JettyInternalConfig.kt
- javalin/src/main/java/io/javalin/config/PrivateConfig.kt
- javalin/src/main/java/io/javalin/jetty/JavalinJettyServlet.kt
- javalin/src/main/java/io/javalin/jetty/JettyResourceHandler.kt
- javalin/src/main/java/io/javalin/jetty/JettyServer.kt
- javalin/src/main/java/io/javalin/plugin/bundled/SslRedirectPlugin.kt
- javalin/src/test/java/io/javalin/TestCustomJetty.kt
- javalin/src/test/java/io/javalin/TestGracefulShutdown.java
- javalin/src/test/java/io/javalin/examples/HelloWorldServlet.java
- javalin/src/test/kotlin/io/javalin/examples/AdvancedServerSentEvent.kt
> [config] Cleanup Jetty config

- javalin/src/main/java/io/javalin/config/BundledPluginsConfig.kt
- javalin/src/main/java/io/javalin/plugin/bundled/DevLoggerPlugin.kt
- javalin/src/test/java/io/javalin/TestLogging.kt
> [devlogplugin] Add option to skip static files

- javalin/src/main/java/io/javalin/util/OptionalDependency.kt
- pom.xml
Bumped versions of some dependencies that have vulnerabilities during a scan.
> dependency upgrade to clear vulnerability

- javalin/src/main/java/io/javalin/http/util/MultipartUtil.kt
We can avoid a few unnecessary allocations while processing request's parts in the `MultipartUtil` class.
> [multipart] Use sequences to process multipart request content

- .github/workflows/main.yml
- .github/workflows/publish-snapshots.yml
This PR does:
- Run tests in Apple silicon
- Fix snapshot publishing
- Bump actions versions
> Bump actions and add new features

- .github/README.md
- .github/workflows/main.yml
- javalin-utils/coverage/README.md
- javalin-utils/coverage/pom.xml
- javalin-utils/pom.xml
- pom.xml
- A module for a full test coverage report whose POM is not published 
- Workflow modifications for publishing coverage reports to _Codecov_
> Add test coverage reports

- .github/dependabot.yml
> [github] Group dependabot PRs

- .github/dependabot.yml
> [revert] "[github] Group dependabot PRs"

- javalin/src/main/java/io/javalin/http/Context.kt
- javalin/src/test/java/io/javalin/TestRequest.kt
> feature: implemented queryParamsAsClass & formParamsAsClass

- javalin-rendering/pom.xml
- javalin/pom.xml
- pom.xml
As a first PR to the project, updating some comparatively non-scary non-breaking dependencies:
* patch version updates
* test dependencies
* maven plugins
I'll continue go through the [dependabot PR](https://github.com/javalin/javalin/pull/2384) suggestions and file separate PR:s.
> Smaller version updates

- javalin-micrometer/pom.xml
For some reason tests failed for this version when I updated to it before, but not now.
> [deps] Update micrometer to 1.14.15, latest release version

- pom.xml
> Revert "[tests] Add java argument to surefire for mockito as a java agent"

- javalin/src/main/java/io/javalin/router/exception/ExceptionMapper.kt
- javalin/src/test/java/io/javalin/TestExceptionMapper.kt
Issue: https://github.com/javalin/javalin/issues/2422
> Fix infinite loop in custom exception handling
